blablacar/ui-library

- CHANGELOG.md
- src/autoComplete/autoCompleteList.tsx
- src/autoComplete/autoCompleteList.unit.tsx
- src/autoComplete/index.tsx
- src/autoComplete/index.unit.tsx
- src/autoComplete/story.tsx
- Reuse the `autoCompleteList` to render the empty search. 
- Fix the condition of display for empty search / item list
- Refactor the loading/checked status of the list items
> Render emptySearch with an autoCompleteList

- CHANGELOG.md
- src/checkbox/__snapshots__/index.unit.tsx.snap
- src/checkbox/index.tsx
- src/checkbox/index.unit.tsx
- src/checkbox/story.tsx
- src/checkbox/style.ts
Add a prop to invert text and checkbox, defaults to checkbox before text.
Prevent empty nodes when labels are missing.
Unify stories into one entry.
> [BBCSPA-1446] Checkbox position change and more

- CHANGELOG.md
- src/warningModal/style.ts
The z-index property for the Modal component is on the dimmer.
I removed the dimmer for WarningModal but forgot to reimplement the correct z-index.
> Add same z-index to WarningModal as Modal

- CHANGELOG.md
- src/pushInfo/__snapshots__/index.unit.tsx.snap
- src/pushInfo/style.ts
- src/uneditableTextField/__snapshots__/index.unit.tsx.snap
- src/uneditableTextField/style.ts
Fixes for UneditableTextField and PushInfo
Loader is still not working but it will require a complete change (no SVG transformation) and not a fix.
PushInfo BEFORE
PushInfo AFTER
UneditableTextField BEFORE
UneditableTextField AFTER
UneditableTextField with icon BEFORE
UneditableTextField with icon AFTER
> [BBCSPA-1490] IE 11 fixes

- CHANGELOG.md
- bin/templates/components.tsx
- src/index.tsx
`flush` and `flushToHTML` exports are not the same.
See usage example: https://github.com/zeit/styled-jsx#styled-jsxserver
> fix `flush` import from `styled-jsx`

- CHANGELOG.md
- src/dropdownButton/index.tsx
- src/dropdownButton/index.unit.tsx
- src/dropdownButton/story.tsx
- src/dropdownButton/style.ts
- src/hamburgerButton/index.tsx
- src/hamburgerButton/index.unit.tsx
This component becomes a controlled component, as the state has been removed. So the behaviour
is consistent with the HamburgerButton.
> [Breaking Change] - DropdownButton no longer handles the dropdown content

- src/avatar/style.ts
I realized that when changing the Avatar size, the size of the Badge was not adjusted accordingly
I wish I wouldn't have to write such overrides though...
> stronger style override for badges in avatar

- CHANGELOG.md
- src/button/style.ts
- src/modal/__snapshots__/index.unit.tsx.snap
- src/snackbar/__snapshots__/index.unit.tsx.snap
Also fix button content ellipsis
> Content of the `<Button>` is now taking 100% of the width

- CHANGELOG.md
- src/checkbox/__snapshots__/index.unit.tsx.snap
- src/checkbox/index.tsx
- src/checkbox/index.unit.tsx
- src/checkbox/story.tsx
- src/checkbox/style.ts
Checkboxes should be able to display API request status when being clicked. It uses the same STATUS prop than Item components and variants for consistency.
Loader replaces the blue check icon, either placed on right or left.
> Checkbox loading state

- CHANGELOG.md
- src/stepper/style.ts
> Stepper value align center

- CHANGELOG.md
- src/button/index.tsx
- src/button/index.unit.tsx
No visual change, but Button is now no longer interactive while in loading or checked state.
> Button is disabled when loading/checked

- CHANGELOG.md
- src/topBar/index.tsx
0.19.0 release broke the styling for the Topbar's children. Looks like `styled-jsx` does not read arrays of components correctly and does not apply its classes to them. Re-applying the styles in each component does the trick, and does not affect the CSS output (it is clever enough to not duplicate the code).
> Fix Topbar children styles

- CHANGELOG.md
- src/textField/index.tsx
- src/textField/index.unit.tsx
- src/textField/story.tsx
The new `format` prop allows to update the value each time it changes. This can be helpful for some inputs where you want the value to match a certain pattern (ex: a date, a phone number) and autofill some characters along.
In the story, I've put an example with a date input where you autofill the slash characters when the user is typing. Be mindful that this updates the value (this is the big difference between the TextField `format` and the Stepper `format` props).
> Add format prop to TextField

- CHANGELOG.md
- src/_utils/item/index.tsx
- src/_utils/item/index.unit.tsx
- src/_utils/item/style.ts
- src/itemInfo/index.tsx
I should have listen @Bidjii 🙇. The breaking change introduced in #173 on margins to have a Pixar hover was too big to be introduced by the item action. It requires a dedicated project so I'm reverting it.
Also forward href props to item component
> Remove breaking change on margin

- CHANGELOG.md
- package-lock.json
- package.json
* [Fix] Remove the breaking change that added horizontal padding on Toggle button and profile in the previous version
* [Fix] Forward href props to the Item component
> Release 0.21.1

- CHANGELOG.md
- src/icon/checkIcon.tsx
After 1 year, 3 months, 10 days this issue is finally fixed 🎉.
| Before | After |
|--------|------|
| ![wrong-animation](https://user-images.githubusercontent.com/2495124/52951800-08083a00-3383-11e9-9605-f740fa6963b5.gif) | ![valid-animation](https://user-images.githubusercontent.com/2495124/52951797-076fa380-3383-11e9-8e55-046ea54e1ce9.gif) |
> Fix check icon animation not played correctly on Safari

- CHANGELOG.md
- src/button/style.ts
- src/textField/index.tsx
- src/textField/index.unit.tsx
We had regressions when importing 0.22.1 version as Button used with links were full width and Button used as TextField add-ons had icon-alignment issues.
This fixes both problems, and also added a missing unit test on the TextField component.
> Set Button to inline-flex to solve alignment issues

- CHANGELOG.md
- src/_utils/branding.ts
- src/itinerary/__snapshots__/index.unit.tsx.snap
- src/itinerary/index.tsx
- src/itinerary/style.ts
To comply with specs and for better accessibility
Before:
After:
> update Itinerary colors

- CHANGELOG.md
- package-lock.json
- package.json
Since we are now using hooks, we can't have 2 versions of React as a dependencies in a host project.
Moving the dependencies as `peerDependencies` will use only one version of React (the one defined in the host project)
More info explained here:
https://reactjs.org/warnings/invalid-hook-call-warning.html
> Move react into peer dependencies

- CHANGELOG.md
- src/tripCard/index.tsx
- src/tripCard/style.ts
> TripCard style fixes

- CHANGELOG.md
- src/itinerary/index.tsx
- src/itinerary/index.unit.tsx
Before:
After:
In both cases, we don't have the `small` property, but we don't have either time or subLabel in places. Especially used for `TripCard` component that don't give us full control over the itinerary.
> Display itinerary as small if we don't provide time or subLabel 

- CHANGELOG.md
- src/_utils/checkboxIcon/__snapshots__/index.unit.tsx.snap
- src/_utils/icon/BaseIcon.tsx
- src/_utils/icon/index.tsx
- src/_utils/item/__snapshots__/Item.unit.tsx.snap
- src/_utils/radioIcon/__snapshots__/index.unit.tsx.snap
- src/datePicker/__snapshots__/DatePicker.unit.tsx.snap
- src/icon/checkIcon.tsx
- src/icon/circleIcon.tsx
- src/itemCheckbox/__snapshots__/ItemCheckbox.unit.tsx.snap
- src/itemChoice/__snapshots__/index.unit.tsx.snap
- src/itemRadio/__snapshots__/ItemRadio.unit.tsx.snap
- src/itemRadioGroup/__snapshots__/index.unit.tsx.snap
- src/itemsList/__snapshots__/ItemsList.unit.tsx.snap
- src/messagingSummaryItem/__snapshots__/MessagingSummaryItem.unit.tsx.snap
- src/modal/__snapshots__/Modal.unit.tsx.snap
- src/phoneField/__snapshots__/PhoneField.unit.tsx.snap
- src/proximity/__snapshots__/Proximity.unit.tsx.snap
- src/pushInfo/__snapshots__/PushInfo.unit.tsx.snap
- src/selectField/__snapshots__/SelectField.unit.tsx.snap
- src/snackbar/__snapshots__/Snackbar.unit.tsx.snap
- src/typings/icons.d.ts
- use styled component keyframes utility to generate the dash and rotator keyframes for Circle icon (this is used by the loader in spinning mode)
- Add missing .kirk-icon-wrapper class for icons with a badge
> CSS-inJS: Fix loader animation

- CHANGELOG.md
- src/profile/index.tsx
- src/profile/index.unit.tsx
- src/title/index.tsx
User name should be display in DISPLAY1 instead of DISPLAY2 for medium profile
This is a regression I introduced in the v10.0.0
*issue*
*fix*
> Fix medium profile display

- CHANGELOG.md
- src/icon/sendIcon.tsx
- src/textarea/Textarea.tsx
- src/textarea/story.tsx
When used with fitContent mode, the Textarea is adapting its height as the user typs in the field. We need to update the height as well when the value of the field is updated programmatically using the defaultValue props.
TESTED=Locally in story book with programmatic and manual modifications of Textarea content.
> Adapt Textarea height when changing programmatically its content in 'fitContent' mode

- CHANGELOG.md
- src/confirmationModal/ConfirmationModal.tsx
- src/confirmationModal/ConfirmationModal.unit.tsx
- src/confirmationModal/story.tsx
> New loading state for confirmation modal

- CHANGELOG.md
- src/icon/busIcon.tsx
- src/icon/carpoolIcon.tsx
- src/icon/index.tsx
- src/tabs/Tabs.tsx
- src/tabs/Tabs.unit.tsx
- src/tabs/__snapshots__/Tabs.unit.tsx.snap
- src/tabs/index.tsx
- src/tabs/story.tsx
Add the possibility to use icons within Tabs.
You can chose to also display the text (label) along with the icon (desktop context). This needed to review the alignment of the different elements withing a tab.
Also added 2 icons that are specific to tabs.
> Bbc 693/tabs icons

- CHANGELOG.md
- src/tabs/Tabs.tsx
- src/tabs/__snapshots__/Tabs.unit.tsx.snap
- src/tabs/index.tsx
- src/tabs/story.tsx
Fixed tabs should have equal width. This wasn't the case as tabs with more content could squish the little ones.
Also, the specs show that a looooong word in a fixed tab should be truncated (ellipsis). This is fixed too.
> force equal width to fixed tabs and ellipsis for long words

- CHANGELOG.md
- src/tabs/index.tsx
> fix for fixed tabs content being left aligned

- CHANGELOG.md
- src/disclaimer/Disclaimer.tsx
- src/disclaimer/Disclaimer.unit.tsx
- src/disclaimer/story.tsx
- Add deprecated rendering for button icon on the right side (used for SRP)
- Add non-caption mode for body text
> Add missing display modes in Disclaimer

- CHANGELOG.md
- src/tabs/Tabs.tsx
- src/tabs/__snapshots__/Tabs.unit.tsx.snap
This is needed to have different layout rules between tabs and their panel contents.
TESTED=Locally in storybook and locally in prod version by copypasting nodes in DOM in inspector.
> Make tab and their panel layouts independent.

- CHANGELOG.md
- src/_utils/branding.ts
- src/itinerary/Itinerary.tsx
- src/itinerary/Itinerary.unit.tsx
- src/itinerary/index.tsx
- src/itinerary/story.tsx
- src/tripCard/TripCard.tsx
- src/tripCard/TripCard.unit.tsx
- src/tripCard/index.tsx
- Set time cell width to 48px (was 64px) + 8px of right padding (was 0)
- Fix a11y for title (it's now a SubHeader outside the list, it was a nested li/text)
- Fix departure/arrival city alignement with dot
- Fix multiple :before/:after elements being created due to non selective CSS rule (div/span)
Itinerary:
Small itinerary:
TripCard:
> Fix Itinerary/TripCard visual alignment and a11y

- CHANGELOG.md
- src/_utils/branding.ts
In publication, we need to change the text color of the stepper depending on the user's price.
> Add textColor prop to Stepper component

- CHANGELOG.md
- src/textarea/Textarea.tsx
- src/textarea/index.tsx
Previously, the scrolling area was including the 16px padding top/bottom. It begets a scrollbar that could go above the rounded corners of the Textarea widget.
With this PR, the top and bottom padding are converted to margin and are not part of the scrollable area anymore, hence there is no overlap anymore between the corners and the scrollbar.
TESTED=Locally in storybook.
> Fix Textarea visual for scrollbar

- CHANGELOG.md
- src/message/Message.tsx
- src/message/Message.unit.tsx
- src/message/index.tsx
- src/message/story.tsx
- Remove a bunch of unused property and not up-to-spec code
- Messages have now proper left/right alignment and can stack properly (author and date were removed)
- Add a new generic annotation field which is added below the Message instead of inside
- Added new story book cases for complex conversation cases
- Added support for very long message or long message without breaks
TESTED=Locally in story book + unit tests for basic structure
> Overhaul Message kirk component

- CHANGELOG.md
- src/timePicker/TimePicker.tsx
- src/timePicker/TimePicker.unit.tsx
- src/timePicker/index.tsx
- src/timePicker/story.tsx
In a similar fashion to TextField, we can now use the `focus` prop on the TimePicker to focus the select when the component is mounted.
Focused style (copied from TextField component):
> Handle TimePicker focus on mount

- CHANGELOG.md
- src/stepper/Stepper.tsx
- src/stepper/index.tsx
Fix the following issue by preventing flex-grow on LARGE display (it's always displayed at 100% of its container).
> Fix random size issue on large stepper

- CHANGELOG.md
- src/datePicker/DatePicker.tsx
- src/datePicker/DatePicker.unit.tsx
In our publication flow, when selecting a date in a far future, we end up in the return date step with all next dates disabled. We have to either scroll down or click next months button until arriving to the first available date.
I'm using the `initialMonth` prop from `react-day-picker` to set it to the `initialDate`.
TESTED: in publication flow, desktop & mobile display
> Set initialMonth in DatePicker

- CHANGELOG.md
- src/tabs/Tabs.tsx
When used in the website with a different url for each tab (with a "tab" query param), using the back button would not trigger an update.
> ensure activeTab is up-to-date when using the back navigation

- CHANGELOG.md
- src/button/index.tsx
- src/datePicker/__snapshots__/DatePicker.unit.tsx.snap
- src/modal/__snapshots__/Modal.unit.tsx.snap
- src/phoneField/__snapshots__/PhoneField.unit.tsx.snap
- src/snackbar/__snapshots__/Snackbar.unit.tsx.snap
Safari 10 do not support flexbox on `<button>` elements, which was causing alignment issues with icons (no visible issue with text buttons).
So bubble-style Button now use `display: inline-block` to fix the issue.
Tested on:
- Safari 10
- Safari 13
- Firefox (latest)
- Chrome (latest)
> Fix alignment issues on Safari 10

- CHANGELOG.md
- src/textarea/Textarea.tsx
The textarea has margins that look like the textarea but won't focus the textarea if clicked.
A click handler was added to  make sure we focus the textarea when clicking these margins.
TESTED=Locally in storybook
> Fix click behavior on textarea to set focus

- CHANGELOG.md
- src/itemAction/index.tsx
- src/itemAction/index.unit.tsx
- src/itemAction/story.tsx
This is needed when rendering many ItemAction in the same page, they don't need to be all highlighted.
TESTED-Unit tests and locally in storybook
> Allow rendering of non-highlighted ItemAction

- CHANGELOG.md
- src/topTripCardList/index.tsx
2 issues fixed:
- The cards were not equal size on large device but dependent on content.
- The padding right scroll hack were not applying because the container didn't have a `position: relative`
See column issue:
> Fix layout issue on TopTripCardList

- CHANGELOG.md
- src/stepper/Stepper.tsx
- src/stepper/Stepper.unit.tsx
- src/stepper/index.tsx
Stepper can now be controlled with keyboard (decrement with left/down, increment with right/up, min with Home, max with End).
It almost looks the same, except for the focus.
It looks like this now in Chrome and Safari:
Unfortunately, I can't get Firefox to show the focus.
> add slider keyboard controls to Stepper

- CHANGELOG.md
- src/itinerary/Itinerary.tsx
- src/itinerary/Itinerary.unit.tsx
- src/itinerary/index.tsx
- src/itinerary/story.tsx
Before:
After:
Context: 
6 months ago, we needed to display small itineraries in Your Rides, but the component is rendered through `TripCard`, so we didn't have lot of room to customize the thing. So I naively assumed that we should display the component as small if we don't have time nor subLabel (that's what the small prop was doing).
Except... that if we want to render itineraries with subLabel but without time, it breaks. 
Initial commit: https://github.com/blablacar/ui-library/commit/b5f58202d1e28ced0dd888476d003e132e084d29
> Fix margin in itinerary if we want to display content without time

- CHANGELOG.md
- src/itinerary/index.tsx
- src/itinerary/story.tsx
> Fix itinerary display with single step

- CHANGELOG.md
- src/stepper/index.tsx
> Fix visible input range track on Safari

- CHANGELOG.md
- src/icon/index.tsx
- src/icon/meetingPoint.tsx
Active:
Inactive:
Icon processed through svgomg + manual optimization after.
> Add MeetingPointIcon

- CHANGELOG.md
- src/theVoice/index.tsx
In the Pixar spec `TheVoice` component have a 30px font size with the following rule:
> When screen width is less than 320px the font size moves down to 26px.
However we don't have a 320px breakpoint and we don't have a 26px font size either. So we will keep the 30px until the specification is clarified. 
| *Before* | *After* |
|-----------|--------|
| ![image](https://user-images.githubusercontent.com/2495124/72447418-95cbef80-37b5-11ea-8b55-6281ac87682b.png) |  ![image](https://user-images.githubusercontent.com/2495124/72447353-7d5bd500-37b5-11ea-8f81-af8cdb9a76c6.png) |
> Fix the font size of TheVoice component on small screens

- CHANGELOG.md
- src/topTripCardList/index.tsx
When we stop scrolling, the cards will get placed so that it's always one full card in the viewport all handled by the browser.
Support is good: https://caniuse.com/#search=scroll-snap
> Added scrolling snap on topTripCardList

- CHANGELOG.md
- src/itinerary/Itinerary.tsx
- src/itinerary/index.tsx
> Removed z-index from itinerary bullets and use source order instead

- CHANGELOG.md
- src/_utils/branding.ts
- src/_utils/itineraryCollapsible/ItineraryCollapsible.tsx
- src/_utils/itineraryCollapsible/ItineraryCollapsible.unit.tsx
- src/_utils/itineraryCollapsible/index.tsx
- src/_utils/itineraryLocation/ItineraryLocation.tsx
- src/_utils/itineraryLocation/ItineraryLocation.unit.tsx
- src/_utils/itineraryLocation/index.tsx
- src/_utils/keycodes.ts
- src/bullet/index.tsx
- src/itinerary/Itinerary.tsx
- src/itinerary/Itinerary.unit.tsx
- src/itinerary/index.tsx
- src/itinerary/story.tsx
I expect a lot of feedback, don't be shy.
Most of the logic found in the previous Itinerary is now in a new component ItineraryLocation.
ItineraryCollapsible can be used in Itinerary to collapse intermediate stopovers.
> Refacto Itinerary with ItineraryLocation + ItineraryCollapsible

- CHANGELOG.md
- src/layout/section/baseSection/baseSection.tsx
- src/layout/section/highlightSection/__snapshots__/index.unit.tsx.snap
- src/layout/section/highlightSection/highlightSection.tsx
- src/layout/section/highlightSection/index.unit.tsx
backgroundClassName becomes className.
className becomes contentClassName and is only attached to the inner content.
> Fix content/background class for sections

- CHANGELOG.md
- src/_utils/itineraryCollapsible/index.tsx
- src/_utils/itineraryLocation/ItineraryLocation.tsx
- src/_utils/itineraryLocation/ItineraryLocation.unit.tsx
- src/itinerary/story.tsx
We actually use `mainLabel` for addresses and `subLabel` for cities.
However, when collapsed, it's better to show the city only.
> Display subLabel instead of mainLabel in Itinerary when collapsed

- CHANGELOG.md
- src/layout/section/tabsSection/__snapshots__/index.unit.tsx.snap
- src/layout/section/tabsSection/index.tsx
- src/layout/section/tabsSection/story.tsx
- src/layout/section/tabsSection/tabsSection.tsx
- src/tabs/Tabs.tsx
- src/tabs/__snapshots__/Tabs.unit.tsx.snap
- src/tabs/index.tsx
- src/tabs/story.tsx
The core issue was: Some responsive layout was both in Tabs, TabsSection and in Kairos. With this PR, the Tabs is just a full width component, no padding, no wrapped. All layout code (reponsive, paddings) is inside TabsSection. The TabsSection is now divided into 2 full witdh subsections (one for the tabs, one for the panels) which are full width (and does not use a BaseSection anymore) and it sets layout contrains on nested elements inside these sub sections. Having this full width subsection for the tab list gives a perfect container to set the full width separator border too: We don't need a double border in Tabs and TabsSection like before.
Complete changelog:
- create two new virtual sections inside the Tabs => one for the tab lists, one for the panels. Each section is full width but …
> Tabs and TabsSection layout overhaul

- CHANGELOG.md
- src/confirmationModal/ConfirmationModal.tsx
- src/confirmationModal/index.tsx
- src/confirmationModal/specifications/confirmationModal.md
- src/confirmationModal/story.tsx
- src/successModal/SuccessModal.tsx
- src/successModal/SuccessModal.unit.tsx
- src/successModal/specifications/successModal.md
- src/successModal/story.tsx
- src/theVoice/TheVoice.tsx
- src/theVoice/index.tsx
- src/theVoice/specifications/theVoice.md
- src/theVoice/story.tsx
- src/title/Title.tsx
Update **Modal** component to receive `TheVoice`
- `TheVoice` component now receive a prop `isInverted` to define its color `title` or `textWithBackground`. It receives a modifier class `.kirk-title--inverted`.
- `ConfirmationModal` and `SuccessModal` now use `TheVoice` component
- Move around **Modals stories** (SuccessModal, ConfirmationModal) to improve discoverability/heuristics. _We could also consider to move folders_
- I've declare `children` as `string` since we had only text as child... **I don't feel its a good practice.. What do you think?!**
It's my first PR, so please be kind! 🗡
> [BBC-5337] Upgrade `Modal` with `TheVoice` component

- CHANGELOG.md
- src/layout/layoutNormalizer.tsx
- src/pages/messaging/brazemarketing.story.tsx
- src/pages/messaging/inbox.story.tsx
- src/pages/ridedetails/carpool.story.tsx
This component role is to install layout normalization CSS **global** rules.
It has a **useLegacyNormalization** mode which is used to import the layout override from production  BBC. When this useLegacyNormalization mode is disabled, the new normalization rules will be used instead (currently empty, it will come in future normalization PRs).
This component will allow us to move layout rules from BBC to kirk and have an easy toggle (controlled by a feature flag) to control the layout normalization mode on production BBC and kirk pages (ridedetails, etc).
> Introduce new LayoutNormalizer component

- CHANGELOG.md
- src/phoneField/PhoneField.tsx
- src/phoneField/__snapshots__/PhoneField.unit.tsx.snap
- src/selectField/SelectField.tsx
- src/textField/TextField.tsx
- **[UPDATE]** Add autoComplete attribute on `SelectField` and `PhoneField` components.
- **[UPDATE]** Change autoComplete type on `TextField` to allow other values than `on` and `off`.
[MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete)
> "tel-country-code"
The country code, such as "1" for the United States, Canada, and other areas in North America and parts of the Caribbean.
> "tel-national"
The entire phone number without the country code component, including a country-internal prefix. For the phone number "1-855-555-6502", this field's value would be "855-555-6502".
> Add autoComplete attribute on SelectField and PhoneField components

- CHANGELOG.md
- src/datePicker/DatePicker.tsx
- src/datePicker/DatePicker.unit.tsx
- src/datePicker/story.tsx
Previously if we selected date in few months and opened the datepicker again. The first available month was the one that have been selected and it was impossible to scroll up to the current month.
> [BBC-6919] Fix Datepicker on small screen.

- CHANGELOG.md
- src/_utils/itineraryLocation/ItineraryLocation.tsx
- src/_utils/itineraryLocation/index.tsx
- src/layout/section/tripsSection/index.tsx
- src/tripCard/TripCard.tsx
- src/tripCard/index.tsx
Allow long text in Itinerary to be truncated, and make price always visible.
Snaps the driver/passenger/flags info at the bottom of the card to align with adjacent cards.
The bottom part has also been refactored to remove cases of empty tags and also truncate the driver name if needed. I also made the name use all the space to the right in case there's no flag to display. If for some reason we have no driver/passenger to display, flags, if any, will stick to the bottom right position.
TESTED = locally on storybook and kairos
> improve tripCard layout and how text truncates

- CHANGELOG.md
- src/messagingSummaryItem/index.tsx
The padding is already being fixed by the <LayoutNormalizer> component.
> Remove horizontal padding override for MessagingSummaryItem

- src/autoComplete/AutoComplete.tsx
- src/searchForm/autoComplete/overlay/AutoCompleteOverlay.tsx
- src/searchForm/autoComplete/overlay/AutoCompleteOverlay.unit.tsx
- src/searchForm/autoComplete/overlay/index.tsx
- src/searchForm/autoComplete/section/AutoCompleteSection.tsx
- src/searchForm/autoComplete/section/AutoCompleteSection.unit.tsx
- src/searchForm/autoComplete/section/index.tsx
- src/searchForm/story.tsx
- src/textField/TextField.tsx
Display `Loader` component when `AutoComplete` loads its autocomplete list
Backward compatibility is preserved and the loader is only visible within search form
> BBC 7140 handle autocomplete loading

- src/datePicker/index.tsx
- src/searchForm/SearchForm.tsx
- src/searchForm/autoComplete/overlay/index.tsx
- src/searchForm/autoComplete/section/index.tsx
- src/searchForm/datePicker/overlay/index.tsx
- src/searchForm/index.tsx
- src/searchForm/specifications/searchForm.md
- src/searchForm/stepper/overlay/index.tsx
- src/searchForm/story.tsx
This PR takes care of:
- fixing some wrong positions on large devices (not as per specs)
- opening overlays when clicking on each button
- keyboard navigation
To be taken care of in other PRs
- Create Overlay component to be reused in all overlay components (autocomplete, stepper & datepicker)
- Add a `format` method prop to format form values e.g. value for stepper is `2` but it should be rendered as `2 seats`
- Interaction on small devices
> Search Form Interactions for large devices

- CHANGELOG.md
- src/typography/display1/index.tsx
`TextDisplay1` doesn't follow the sizing scale
-  Follow **font** scale at `_utils/branding`
> [BOYSCOUT] FIX `TextDisplay1` typographic scale

- src/searchForm/SearchForm.tsx
- src/searchForm/SearchForm.unit.tsx
- src/searchForm/story.tsx
Done in this PR:
- Added `format()` prop
- Kept selected value for Stepper and Datepicker when reopening them
- Added unit tests on interaction and formatting
To be done in next PRs
- Handling placeholders & formatting for Autocomplete
> Added format prop to SearchForm

- .storybook/config.js
Configure [storybook viewport addons ](https://github.com/storybookjs/storybook/tree/master/addons/viewport) to be able to test on common devices on the market.
Improve testability
> [BOYSCOUT] Config Default Viewports to improve device testing

- CHANGELOG.md
- src/datePicker/DatePicker.tsx
On large screen we can navigate through calendar with arrow buttons and we can display dates in far future.
The calendar will now display dates until 1 year by default
> [BBC-7444] Calendar is limited to 1 year

- CHANGELOG.md
- src/_utils/checkboxIcon/__snapshots__/index.unit.tsx.snap
- src/_utils/radioIcon/__snapshots__/index.unit.tsx.snap
- src/itemCheckbox/__snapshots__/ItemCheckbox.unit.tsx.snap
- src/itemChoice/__snapshots__/index.unit.tsx.snap
- src/itemRadio/__snapshots__/ItemRadio.unit.tsx.snap
- src/loader/Loader.tsx
- src/loader/Loader.unit.tsx
- src/loader/index.tsx
- src/loader/story.tsx
Loader overhaul:
- introduce a new **layoutMode** enum prop that can be in **inline** (existing), **fullscreen**( existing) or **block** (new) modes. The **block** mode renders the loader as a block (in the sense 'CSS block formatting context' with some top/bottom padding and centering the loader horizontally. This new block mode is used a bunch of time in BBC by using duplicated code like:
`<div className="flex justify-center">
<Loader inline />
</div>`
- The **inline** prop is commented as deprecated since it's a particular and simpler case of the layoutMode prop. It will be removed in a later PR to avoid a big breaking change. The new loader will be fuly backward compatible with existing cases.
- Fix the size param when using the fullscreen mode; previously it was broken and was …
> Loader overhaul + new BLOCK mode

- .babelrc
- CHANGELOG.md
- package-lock.json
- package.json
- src/_utils/assert.ts
- src/datePicker/__snapshots__/DatePicker.unit.tsx.snap
- src/hint/__snapshots__/index.unit.tsx.snap
- src/layout/section/mediaContentSection/__snapshots__/index.unit.tsx.snap
- src/modal/__snapshots__/Modal.unit.tsx.snap
- src/phoneField/__snapshots__/PhoneField.unit.tsx.snap
- src/review/__snapshots__/Review.unit.tsx.snap
- src/snackbar/__snapshots__/Snackbar.unit.tsx.snap
- src/successModal/SuccessModal.tsx
- src/successModal/SuccessModal.unit.tsx
- src/successModal/index.tsx
- src/successModal/story.tsx
- src/typography/Text.tsx
**Same same but different**
https://www.loom.com/share/4dd212b8d87b45eeae1fe77f19da08d1
Follow new specs to layout `ModalSuccess`. 
- Override `Modal`
- Use `styled-components` to override/style components
- Since using `styled-components`, no more classes, so converting `classes` to `data-test`
- **chore**: Install a plugin babel to help on debugging
- Converting classes to data-tests
> [BBC-6997] Responsive`ModalSuccess`

- CHANGELOG.md
- src/review/__snapshots__/Review.unit.tsx.snap
- src/typography/body/index.tsx
- src/typography/subHeader/index.tsx
- src/typography/title/index.tsx
Some missing semi-colons are causing styles to be generated as:
```css
font-weight: 400 line-height:24px;
```
Add a semi-colon at the end of a CSS line.
For the `TextBody` screenshots bellow, only the `line-height` fix is visible as `font-weight: 400` is the default one.
With storybook. I also updated some (invalid) snapshots.
| Component        | Before           | After  |
| ------------- |-------------| -----|
| `TextBody` | <img width="110" alt="Screenshot 2020-04-20 at 18 09 32" src="https://user-images.githubusercontent.com/17502801/79775790-0ba3a200-8335-11ea-8216-a86ac9849998.png"> | <img width="113" alt="Screenshot 2020-04-20 at 18 10 02" src="https://user-images.githubusercontent.com/17502801/79775894-30981500-8335-11ea-9c57-378a4532a3fe.png"> |
| `TextSubHeader` | <img …
> [BOYSCOUT] Fix typography invalid styles

- CHANGELOG.md
- src/_utils/branding.ts
- src/_utils/mediaSizeProvider/index.tsx
- src/layout/columns/__snapshots__/index.unit.tsx.snap
- src/layout/section/highlightSection/__snapshots__/index.unit.tsx.snap
- src/layout/section/mediaContentSection/__snapshots__/index.unit.tsx.snap
- src/layout/section/tabsSection/__snapshots__/index.unit.tsx.snap
- src/modal/__snapshots__/Modal.unit.tsx.snap
The issue was that depending on how we write media queries based on small or large breakpoints, the rendering would differ when the screen is 800px. 
It also broke the mediaSizeProvider which we could in certain case like in the search form returning large instead of small.
See example below: rendering on 800px screen, we should have Divider between the fields which are based on MediaSizeProvider returning large
Have exclusive values for large and small fixes the issue
This also makes it consistent with the logic we have in the SPA on breakpoints.
Tested locally on storybook
> Fix breakpoints values to make them exclusive betweens small & large

- CHANGELOG.md
- src/modal/Modal.tsx
- src/successModal/SuccessModal.tsx
`ModalProps` hasn't been found when extended on other components.
_SPA_ is not able to resolve the 'modal' path (which is normal because it has no way of knowing where to find it), the issue will appear for every type that reference at least one from another file.
- update path
- Convert **interface** into **type**
-  **Manually** fixing it on node_modules
> [Fix] Resolve `ModalProps` path

- CHANGELOG.md
- src/layout/section/heroSection/heroSection.tsx
- src/layout/section/heroSection/index.tsx
- src/layout/section/heroSection/index.unit.tsx
- src/layout/section/heroSection/story.tsx
The `HeroSection` component now support 2 contents:
- A link to the search page (deprecated)
- The `SearchForm` component
**DEMO**
Desktop: 
Mobile: 
**TESTED**: Unit test and manually on Chrome, Firefox and Safari
> Update hero section to accept search form

- CHANGELOG.md
- src/hint/HintBubble.tsx
- src/hint/__snapshots__/index.unit.tsx.snap
When the content of the hint is too long the cross is cropped. This PR fixes it.
Just add a `flex: 1`.
Tested locally in storybook
> Fix the Hint close icon when the content is too long

- .github/PULL_REQUEST_TEMPLATE.md
Fix the typo in the Github issue template "How was it was tested" => "How it was tested".
Remove the 2nd "was".
Not much.
I wasn't 🤷‍♂️.
> Fix typo in github issue template

- src/_utils/index.tsx
- src/_utils/index.unit.tsx
- src/avatar/Avatar.tsx
- src/button/Button.tsx
- src/buttonGroup/ButtonGroup.tsx
- src/datePicker/DatePicker.tsx
Simplify the `prefix` usages for custom prefixes.
The `baseClass` parameter of `prefix` is now added to the `'kirk'` prefix instead of replacing it.
```ts
const BASE_CLASSNAME = prefix({ 'button-group': true })
// ↓↓↓
const BASE_CLASSNAME = 'button-group'
```
I also split the tests into specific unit tests.
Unit tests.
> Simplify CSS prefix function

- CHANGELOG.md
- src/buttonGroup/ButtonGroup.tsx
- src/buttonGroup/ButtonGroup.unit.tsx
- src/datePicker/DatePicker.tsx
- src/datePicker/DatePicker.unit.tsx
The base class name of `DatePicker` and `ButtonGroup` are missing the "kirk" prefix.
Add the missing prefix to the component's base class names.
🤷‍♂️
I added a test for that in each component.
> Fix missing CSS prefix for DatePicker and ButtonGroup

- CHANGELOG.md
- src/theVoice/TheVoice.tsx
- src/theVoice/index.tsx
- src/theVoice/specifications/theVoice.md
- src/theVoice/story.tsx
TheVoice spacing not follow spec
- Update spacings
- Converting **margin** to **padding** to avoid collapse
- Rewrite style on **mobile-first**
- Reduce **styled-components** specificity
- Remove `isInverted` class
- _Manually_ 🤙
> [BOYSCOUT] Update spacing on TheVoice

- CHANGELOG.md
- src/itemCheckbox/ItemCheckbox.tsx
- src/itemCheckbox/story.tsx
- src/itemInfo/index.tsx
- src/pages/yourrides/offer/editOptions.story.tsx
- stories/index.tsx
- Add the `leftAddon` option to `ItemCheckbox` to allow having an icon.
- Add edit your publication options screen in storybook
They're is still hard-coded styles in the story. I'll need to update this in other PRs
Storybook, mobile & desktop layout, chrome.
> [BBC-7928] Allow icon in ItemCheckbox

- CHANGELOG.md
- src/layout/content/content.tsx
- src/layout/content/story.tsx
- Fixed the role='presentation' that was breaking the a11y of the MainContent when used as a <Form> (most of our cases are doing this)
- Added new Form specific attributes to avoid TypeScript errors on unknown attributes.
TESTED=Locally
> Fix MainContent Form props and a11y

- CHANGELOG.md
- src/pages/yourrides/offer/editOptions.story.tsx
- src/pages/yourrides/offer/editPrice.story.tsx
- src/stepper/Stepper.tsx
- src/stepper/Stepper.unit.tsx
- src/stepper/index.tsx
- src/stepper/story.tsx
- stories/index.tsx
Allows rendering a vertically-centered component on the left of small steppers.
- Updated example for Edit your trip options
- Add example for Edit your trip price (also used during publication)
- Add `leftAddon` option to `Stepper`
- Updated unit tests
- Updated related pages
- Removed custom CSS!
Storybook with small/large layouts, chrome + unit tests
> Add leftAddon option to Stepper

- CHANGELOG.md
- src/itemChoice/index.tsx
- src/itemData/index.tsx
Update `mainInfo` type from `string` to `React.ReactNode`
> Fix mainInfo prop type in ItemData (from string to React.ReactNode)

- CHANGELOG.md
- src/message/index.tsx
Allow break-lines via CSS
_Storybook_ 📕
> [BBC-5902] Allow break-lines on `Message`

- CHANGELOG.md
- src/_utils/focusVisibleProvider/index.tsx
- src/_utils/focusVisibleProvider/index.unit.tsx
- src/_utils/focusVisibleProvider/useFocusVisible.unit.tsx
Add optional prop to set a global className with FocusVisibleProvider
It provide a global selector for Components/Elements which not use the focusContext for now.
It merge the behavior we already have on Kairos.
- Locally with the Why component which already use the context 
- Unit tests with/without the new prop added
> Add optional prop to set a global className with FocusVisibleProvider

- CHANGELOG.md
- src/itinerary/index.tsx
We have inconsistency on vertical spacing on Itinerary in the SPA. To fix that we should use the vertical spacing given by the specs and set it in the component itself. Once done we need to remove custom styles that we set on SPA
Adding top padding on Itinerary component
Tested on storybook
> Added padding-top on Itinerary

- CHANGELOG.md
- src/layout/section/heroSection/heroSection.tsx
The new `HeroSection` no longer use a _small_ image  for small screen.
Make `heroImageUrl` optional.
`heroImageUrl` is only used in the deprecated small styles.
With the TS Compiler.
> Make heroImageUrl prop optional in HeroSection

- CHANGELOG.md
- src/searchForm/SearchForm.tsx
- src/searchForm/index.tsx
Export type used by `SearchForm`.
All types used by the `SearchForm` are now exported.
Some generic types have been renamed to be specific to the `SearchForm`.
Unit tests
> Export SearchForm's types

- CHANGELOG.md
- src/_utils/closest.tsx
MainContent component was crashing on IE11 with an error on `matches` function from the `closest` polyfill.
Event though the polyfill was taken from Mozilla, we didn't check that everything was compatible with IE11 (and the `matches` function wasn't). So I've added the polyfill for it since it was pretty simple.
Tested locally on IE11 through Saucelab. Prod version was crashing, while new version wasn't, so I guess it's ok ^^
> Fix crash on IE11 with MainContent component

- CHANGELOG.md
- src/searchForm/SearchForm.tsx
- src/searchForm/SearchForm.unit.tsx
- src/searchForm/datePicker/overlay/DatePickerOverlay.tsx
- src/searchForm/datePicker/overlay/DatePickerOverlay.unit.tsx
- src/searchForm/datePicker/overlay/index.tsx
- src/searchForm/datePicker/section/DatePickerSection.tsx
- src/searchForm/datePicker/section/DatePickerSection.unit.tsx
- src/searchForm/story.tsx
Support custom `DatePicker` component in `SearchForm`.
An optional `renderDatePickerComponent` has been added.
Nothing.
- Unit tests
- Local build in Kairos
> Add renderDatePickerComponent prop in SearchForm

- CHANGELOG.md
- src/searchForm/SearchForm.tsx
- src/searchForm/index.tsx
- src/searchForm/story.tsx
When departure and arrival addresses are too long they overflow.
Update styles to add ellipsis on the texts.
**Before**
**After**
- Storybook (Chrome, Firefox, Safari)
> Add ellipsis for overflowing text in SearchForm

- CHANGELOG.md
- src/searchForm/stepper/section/StepperSection.tsx
- src/searchForm/stepper/section/index.tsx
Display "Continue" button at the bottom in number of passenger step in the search form for small screens.
Update styles to allow that.
**Before**
**After**
- Storybook (Chrome, Firefox, Safari)
> Display "Continue" button at the bottom in number of passenger step

- CHANGELOG.md
- src/layout/section/mediaContentSection/__snapshots__/index.unit.tsx.snap
- src/layout/section/mediaContentSection/index.tsx
- src/layout/section/mediaContentSection/index.unit.tsx
- src/layout/section/mediaContentSection/mediaContentSection.tsx
- src/layout/section/mediaContentSection/story.tsx
We want to stack MediaContentSection, so we need to be able to flip the image and text columns so that it looks good (UX approved).
Tested locally on MacOS with Firefox/Chrome/Safari
> add flipped prop to MediaContentSection

- CHANGELOG.md
- src/searchForm/autoComplete/section/AutoCompleteSection.tsx
- src/searchForm/story.tsx
Fix the alignment of the back button in the search form autocomplete sections.
**Before**
**After**
Override the button styles for this "specific" usage. It doesn't look supported 🤷‍♂️.
Don't we have a generic component for this?
- Storybook
> Fix back button alignment in SearchForm autocomplete sections

- CHANGELOG.md
- src/itemCheckbox/ItemCheckbox.tsx
- src/itemCheckbox/ItemCheckbox.unit.tsx
- src/itemCheckbox/index.tsx
- src/itemRadio/ItemRadio.tsx
- src/itemRadio/ItemRadio.unit.tsx
- src/itemRadio/index.tsx
Impact both `ItemCheckbox` & `ItemRadio` components. Demo for `ItemCheckbox`:
Before:
After:
- Remove `cursor: pointer` when `disabled` is true
- Set `isClickable` prop to false when `disabled` is true to remove the background 
Some snapshots will be updated when upgrading kairos
With storybook
> Remove hover & pointer on disabled ItemCheckbox

- CHANGELOG.md
- src/stepper/Stepper.tsx
- src/stepper/Stepper.unit.tsx
- src/stepper/story.tsx
For trip edit, we need to be able to disable the stepper (i.e., the driver can't update the seat count if a booking is in progress).
We could cheat by setting min/max values equal to the selected value, but MEH.
Added `disabled` prop to the `Stepper` component
Reusing the disabled display we have when hitting min/max values
Storybook on chrome
> Add disabled prop to Stepper

- CHANGELOG.md
- src/paragraph/index.tsx
- src/paragraph/story.tsx
- src/review/__snapshots__/Review.unit.tsx.snap
Paragraph is not breaking anymore when puttin long unbreakable strings (like urls)
TESTED=Locally in stories. new story added to cover this case.
> Make Paragraph resilient to long unbreakable text

- .storybook/knobs.ts
- CHANGELOG.md
- package-lock.json
- package.json
- src/_utils/branding.ts
- src/searchForm/SearchForm.tsx
- src/searchForm/SearchForm.unit.tsx
- src/searchForm/SlideSwitchTransition.tsx
- src/searchForm/index.tsx
- src/searchForm/overlay/index.tsx
- src/searchForm/story.tsx
Add animation between "from" and "to" fields in the `SearchForm` when the user click on the invert button.
- Create a `SlideSwitchTransition` component to manage this CSS transition.
- Use it in the `SearchForm`.
**Result**
react-transition-group had to be updated to the last version to use `SwitchTransition`.
- Storybook: Chrome, Firefox, Safari, Edge
- Unit tests
> Add invert animation in the search form

- CHANGELOG.md
- src/_utils/checkboxIcon/__snapshots__/index.unit.tsx.snap
- src/_utils/icon/index.tsx
- src/_utils/item/__snapshots__/Item.unit.tsx.snap
- src/_utils/radioIcon/__snapshots__/index.unit.tsx.snap
- src/datePicker/__snapshots__/DatePicker.unit.tsx.snap
- src/hint/__snapshots__/index.unit.tsx.snap
- src/itemCheckbox/__snapshots__/ItemCheckbox.unit.tsx.snap
- src/itemChoice/__snapshots__/index.unit.tsx.snap
- src/itemRadio/__snapshots__/ItemRadio.unit.tsx.snap
- src/itemRadioGroup/__snapshots__/index.unit.tsx.snap
- src/itemsList/__snapshots__/ItemsList.unit.tsx.snap
- src/messagingSummaryItem/__snapshots__/MessagingSummaryItem.unit.tsx.snap
- src/modal/__snapshots__/Modal.unit.tsx.snap
- src/phoneField/__snapshots__/PhoneField.unit.tsx.snap
- src/proximity/__snapshots__/Proximity.unit.tsx.snap
- src/pushInfo/__snapshots__/PushInfo.unit.tsx.snap
- src/searchRecap/__snapshots__/SearchRecap.unit.tsx.snap
- src/selectField/__snapshots__/SelectField.unit.tsx.snap
- src/snackbar/__snapshots__/Snackbar.unit.tsx.snap
- src/tabs/__snapshots__/Tabs.unit.tsx.snap
BBC Icons have a irregular stroke, to try to reduce this difference I've used `stroke` attributes to set colors` but it makes the icon look stronger than they really are.
**STROKE**
Back to the old fill version, still irregular, but _we don't see them_
**FILL**
👀  eyes
> Restoring Icons Fill

- CHANGELOG.md
- src/itemsList/ItemsList.tsx
This will fix our garbled UserMenu (broken icons and links) and remove the start up console error (about bad hydratation of SSR UserMenu) in DEV mode.
TESTED=Locally
> Fix ItemsListDivider type comparison when using react-hot-loader

- CHANGELOG.md
- src/_utils/rideAxis/index.tsx
- src/searchRecap/__snapshots__/SearchRecap.unit.tsx.snap
Support longer texts on `RideAxis`. 
**BEFORE:**
**AFTER:**
-  No official specs from Pixar
- Applied to *Search History*
> [boyscout] RideAxis polish style

- CHANGELOG.md
- src/_utils/icon/index.tsx
Reverting fill to stroke on disabled icons
Used stroke instead of fill
Don't mind the spacing in screenshots, it's due to the screenshots themselves
Storybook
Before:
After:
> Fixed stepper icons

- src/buttonGroup/ButtonGroup.style.tsx
- src/buttonGroup/ButtonGroup.tsx
- src/buttonGroup/index.tsx
- src/disclaimer/index.tsx
- src/divider/index.tsx
- src/emptyState/index.tsx
- Export components as **Default** to  avoid breaking changes on BBC App
- [Boyscout] Move ButtonGroup style to another file
- canary
> FIX exports to avoid breaking change

- CHANGELOG.md
- src/searchForm/SearchForm.tsx
- src/searchForm/SearchForm.unit.tsx
- src/searchForm/index.tsx
- src/searchForm/story.tsx
Add `initialFrom` and `initialTo` to prefill the form. The values are placed instead of the placeholder.
Add `disabledFrom` and `disabledTo` to disable From and To inputs. It is not clear if we'll use it but it's a safe move in case we want to protect the initial values.
With `initialFrom` = "Grenoble" (and `disabledTo` set to true but it doesn't show)
I didn't change the story to MDX yet. The original story has a case for each component of the Search Form so I'd rather separate the update in another PR.
Tested locally on Firefox within the main project.
> add SearchForm props initialFrom initialTo disabledFrom disabledTo

- CHANGELOG.md
- src/itemAction/index.tsx
- src/itemBigData/index.tsx
- src/itemData/index.tsx
- src/itemEditableInfo/index.tsx
The last update to the Item components broke the linter on the SPA project, as props are missing.
They were not exported in the new index files.
> add missing props exports in several Item components

- CHANGELOG.md
- src/modal/Modal.tsx
- src/modal/__snapshots__/Modal.unit.tsx.snap
- src/modal/index.tsx
Add prop noHorizontalSpacing to remove horizontal padding on modals.
Locally + snapshot unit test on CSS.
No story since this is only some internal flag that we don't want to expose in the storybook.
> Add prop noHorizontalSpacing to remove horizontal padding on modals

- package.json
Set the port number of Storybook to `4000` so developers don't have to change tabs each time it is launched.
Add the `-p` option to the Storybook CLI.
This shouldn't affect much developers who didn't care about this feature.
By launching Storybook multiple times 👌.
> Set storybook port number

- CHANGELOG.md
- src/layout/section/tabsSection/__snapshots__/index.unit.tsx.snap
- src/tabs/tabs.style.tsx
Removed margin bottom on `Tabs` as specs.
Locally in storybook and in SPA where we have tabs
> Removed tabs margin bottom as specs

- CHANGELOG.md
- src/_internals/item/__snapshots__/Item.unit.tsx.snap
- src/filterBar/FilterBar.style.tsx
- src/itemCheckbox/__snapshots__/ItemCheckbox.unit.tsx.snap
- src/itemChoice/__snapshots__/index.unit.tsx.snap
- src/itemRadio/__snapshots__/ItemRadio.unit.tsx.snap
- src/itemRadioGroup/__snapshots__/index.unit.tsx.snap
- src/itemsList/__snapshots__/ItemsList.unit.tsx.snap
- src/layout/layoutNormalizer.tsx
- src/layout/section/itemsSection/__snapshots__/index.unit.tsx.snap
- src/messagingSummaryItem/__snapshots__/MessagingSummaryItem.unit.tsx.snap
- src/modal/Modal.tsx
- src/modal/__snapshots__/Modal.unit.tsx.snap
- src/modal/index.tsx
- src/modal/story.tsx
Layout for Modal that will be used for Filters feature in SPA
- Used styled components `ModalBody` `ModalFooter` `ModalFog` 
- Kept current modal retro-compatible
- Removed `!important` from `normalizeHorizontally`, I checked and it has no impact.
- Couldn't really unit test this, I'd like to move the modal to RTL in a next PR
- This new layout should be moved out of the `Modal` and should be a Page layout, but right now we need this to progress on the filtres feature
Storybook locally
> Modal Layout for Filters

- CHANGELOG.md
- src/_internals/checkboxIcon/__snapshots__/index.unit.tsx.snap
- src/_internals/radioIcon/__snapshots__/index.unit.tsx.snap
- src/button/Button.unit.tsx
- src/itemCheckbox/__snapshots__/ItemCheckbox.unit.tsx.snap
- src/itemChoice/__snapshots__/index.unit.tsx.snap
- src/itemRadio/__snapshots__/ItemRadio.unit.tsx.snap
- src/loader/Loader.style.tsx
- src/loader/Loader.tsx
- src/loader/Loader.unit.tsx
Implement basic Loader a11y:
- add role progressbar on loader itself (it had no role before)
- use aria-valuetext for the progressbar with the default non-localized value: loading and loaded
- allow customization of these loading and loaded strings with 2 new optional props loadingAriaLabel and loadedAriaLabel
- Add a new non-visual role=status element to get announcements when the state changes (the progressbar does not do that).
It's only basic a11y since that will solve discoverability for screenreaders and tests (selection with a11y-based react testing lib queries).
Still needs to be done to be considered complete a11y-wise:
- the state announcement should be done using some programmatic announcer instead of this role=status. That will allow us to get rid/factorize properly the …
> Implement Loader basic a11y

- CHANGELOG.md
- src/grip/Grip.tsx
When integrating the component in the page, got a warning and then an error caused by `useEffect` not returning a function in all cases. This fixes it :)
Tested locally with the integration in our application.
> Fix Grip crashing on useEffect cleanup

- CHANGELOG.md
- src/searchForm/SlideSwitchTransition.tsx
Expanded the click area on search form from & to fields
Turned `span` animation container into a `div`
Tested the animation between from & to, I didn't notice any regression
Storybook
> Fixed click areas too small on SearchForm

- stories/stories.css
Canvas displays stories way to close to the border. 
Improve visibility / style / presentation of each component avoiding using `<Section />` component for that
**BEFORE**
**AFTER**
- add some style to Storybook element root
- I've chosen do not to wrap stories with a style decorator since it applied to Canvas and Docs. Since are looking for only style storybook, I've used stories.css as the way to go.
- Used same values as `Sbdocs` and `BaseSection` component
- 👀  visually
> [BBC-9295]  Center canvas layout to some ui delight

- CHANGELOG.md
- src/autoComplete/AutoComplete.tsx
- src/searchForm/baseStyles.tsx
- src/searchForm/story.tsx
The loader was misplaced because the className that targeted it had been removed.
I added a specific className for the autocomplete loader so we no longer have coupling between Loader & Autocomplete.
To have the loader in SPA, we'll need to use the `embeddedInSearchForm` prop. I'll prepare a branch with this.
Storybook locally
> Fixed non displayed loader in autocomplete searchform

- src/avatar/Avatar.unit.tsx
Rewrite Avatar's tests with RTL.
The component is not fully accessible which cause some tests to depend on tag names. 
- Unit tests
> Refactor Avatar tests with RTL

- CHANGELOG.md
- src/itemCheckbox/ItemCheckbox.story.mdx
- src/itemCheckbox/ItemCheckbox.style.tsx
- src/itemCheckbox/ItemCheckbox.tsx
- src/itemCheckbox/ItemCheckbox.unit.tsx
- src/itemCheckbox/__snapshots__/ItemCheckbox.unit.tsx.snap
Apply the FocusVisible context to ItemCheckbox to solve keyboard navigation focus ring
Locally:
https://www.loom.com/share/ccd316b85ad44efe84a1e4d5a3f2a1eb
> Display itemCheckbox focus ring on keyboard nav

- CHANGELOG.md
- src/itemEditableInfo/ItemEditableInfo.story.mdx
- src/itemEditableInfo/itemEditableInfo.tsx
- src/itemEditableInfo/itemEditableInfo.unit.tsx
Fix keyboard navigation:
- Use `<button>` instead of `<div role="button">` to make it focusable
- Use the FocusVisibleProvider to display the focus ring
Locally:
https://www.loom.com/share/7864c97601ad422a83e8768e80ca5d26
> Bbc 9604 fix a11y item editable info button

- CHANGELOG.md
- src/layout/section/mediaContentSection/__snapshots__/index.unit.tsx.snap
- src/layout/section/mediaContentSection/mediaContentSection.tsx
- src/layout/section/mediaContentSection/mediaContentTitle.tsx
Noticed a display issue on BBC homepage on mobile device. 
What it looks like:
What it should looks like:
Issue was introduced via 9c4dffecad14de4bc51f54461d0f4fd5222b4cfd. `SubHeader` component has default margins, but it has been replaced by a `TextDisplay1`.
Just wrapped the component to add some style.
Snapshots will have to be updated
Storybook + locally on kairos
> [BBC-9714] Fix MediaContentSection display

- CHANGELOG.md
- src/emptyState/EmptyState.story.mdx
- src/emptyState/EmptyState.tsx
- src/emptyState/EmptyState.unit.tsx
Update EmptyState so that "text" prop can also be a JSX element. It still defaults to a "Title" component if a string is provided.
Context: for SEO purposes, we want to be able to add more info in the title but with different styles (else you might end up with the inclusion of a very long city name written as a big title).
Tested locally on Firefox, with a canary deployment to test in the main app.
> Update text prop to allow jsx element in EmptyState

- CHANGELOG.md
- src/button/index.tsx
- src/button/story.tsx
- src/datePicker/__snapshots__/DatePicker.unit.tsx.snap
- src/hint/__snapshots__/Hint.unit.tsx.snap
- src/icon/redCircleIcon.tsx
- src/layout/section/mediaContentSection/__snapshots__/MediaContentSection.unit.tsx.snap
- src/modal/__snapshots__/Modal.unit.tsx.snap
- src/phoneField/__snapshots__/PhoneField.unit.tsx.snap
- src/snackbar/__snapshots__/Snackbar.unit.tsx.snap
Fixed wrong spacing between icon & text in Button component
- Re-exported `RedCircleIcon` which was not exported properly from Figma and resulted in an icon of 16x16px instead of 24x24px
- Removed negative margins and use the same as design specs (8px right margin on icon)
Storybook locally
> Fixed wrong spacing between icon & text in Button component

- CHANGELOG.md
- src/layout/section/tabsSection/__snapshots__/index.unit.tsx.snap
- src/tabs/tabs.style.tsx
Make sure all diacritics are properly displayed in the tabs.
Set the line height to `normal`: it's the default value.
**Before**
**After**
For accessibility, the line-height should be at least 1.5, `normal` is roughly around 1.2.
- Storybook
> Increase line-height in tabs to support all diacritics

- CHANGELOG.md
- src/grip/Grip.tsx
- src/grip/Grip.unit.tsx
- src/layout/section/slideSection/SlideSection.style.tsx
- src/layout/section/slideSection/SlideSection.tsx
No change on external API for SlideSection, two new optional callbacks for Grip (so no issue with backward compatibility). First version was really basic, now the panel follows the finger before snapping to one of the three set positions. I had delayed this feature until later in the project as it wasn't as critical as others.
Transition effect is only active for the snap feature and when changing the position, so when moving your finger around or during initial mount, there is no animation, making it look super fluid.
Chrome latest version, Firefox latest version, Safari iOS 13
> Grip v2 now with snap effect

- __mocks__/focus-trap.ts
- bin/jestScript.js
- package-lock.json
- package.json
- src/searchForm/SearchForm.tsx
- src/searchForm/SearchForm.unit.tsx
In preparation of updates on the `SearchForm`, update its tests to use RTL.
- Replace Enzyme by RTL in tests.
- Improve focus-trap mock.
- Make sure react-transition-group transitions are immediate in tests.
- Reset `window.innerWidth` after each test for a nicer small/large screen testing.
- Add jest-date-mock to make sure to control the current date.
Nothing.
- Unit tests.
> Use RTL in SearchForm tests

- CHANGELOG.md
- src/_internals/item/Item.tsx
- src/_internals/item/Item.unit.tsx
When creating an Item (or derived ItemAction) using an HTML button tag,  there is no default type used.
By default, the browser (at least Chrome) considers that the button type is 'submit' and not 'button'.
It leads to issues in forms having one submit button plus (at least) another ItemAction button (inside the form). When emitting the submit event in the form, the browser will pick the first type='submit' in the form and activate it. If a button without an explicit type comes before the submit button, it will be activated first.
The fix is to add an explicit type='button' on non-submit buttons as explained here: https://stackoverflow.com/questions/4763638/enter-triggers-button-click
TESTED=Unit tests
> Add explicit type='button' to Item using an HTML button to avoid accidental activations

- CHANGELOG.md
- src/_internals/item/Item.tsx
- src/_internals/item/Item.unit.tsx
In some case a HTML type='button' was added to some anchor-based Items.
Explanation
When using a tag button with an href containing an html anchor to configure an Item e.g.
`<Item tag={<button />} href={<a href='slug_link'>} />`
The resulting HTML was:
`<a href='slug_link' type='button' />`
The tag value inside the tag attribute was taking over the tag value inside the href to decide the HTML type.
The code was modified (and simplified) to cover this case.
A unit tests was added for this edge case.
TESTED=Unit tests.
> Do not add type=button to anchor Items

- CHANGELOG.md
- src/grip/Grip.tsx
Touching the media component (ex: map zooming) would trigger the `Grip` `onTouchMove` and `onTouchEnd` callbacks. Looks like I wasn't checking my refs right...
Fixed the condition that was checking that a previous `touchstart` event was done on the Grip itself before triggering `move` and `end` events.
Locally with Chrome and iOS Safari
> Fix external touch events triggering Grip touch callbacks

- CHANGELOG.md
- src/tripCard/TripCard.style.tsx
Fix `statusInformation` position in `TripCard`
After: 
Before: 
Override item padding in `TripCard` styles
Had to use `!important` cause `Item`s are using it...
Storybook
> Fix `statusInformation` padding in `TripCard`

- CHANGELOG.md
- src/tripCard/TripCard.story.mdx
- src/tripCard/TripCard.tsx
- src/tripCard/TripCard.unit.tsx
Allow the TripCard component to display a sub text in the driver section.
Add an optional `subText` attribute in the `driver` prop.
The `driver` prop makes no sens for buses but until we change it, `subText` should be near `ratings` as it is displayed in its place.
- Storybook
- Unit tests
> Support trip changes in trip card

- CHANGELOG.md
- src/itemRadio/ItemRadio.tsx
We're using `labelTitle` for the `ReasonStep` in kairos, so this field shouldn't be required
Updated type
On kairos
> Set label as optional in ItemRadio

- CHANGELOG.md
- src/breadcrumb/Breadcrumb.tsx
- src/breadcrumb/Breadcrumb.unit.tsx
BEFORE
AFTER
Tested locally on Firefox Macos
> change separator character used in breadcrumb

- CHANGELOG.md
- src/textField/TextField.tsx
> Add missing `spellCheck` prop to `TextField`

- CHANGELOG.md
- src/button/index.tsx
- src/caption/Caption.tsx
- src/caption/Caption.unit.tsx
- src/datePicker/__snapshots__/DatePicker.unit.tsx.snap
- src/hint/__snapshots__/Hint.unit.tsx.snap
- src/layout/section/mediaContentSection/__snapshots__/MediaContentSection.unit.tsx.snap
- src/modal/__snapshots__/Modal.unit.tsx.snap
- src/phoneField/__snapshots__/PhoneField.unit.tsx.snap
- src/review/Review.story.mdx
- src/review/Review.tsx
- src/review/Review.unit.tsx
- src/snackbar/__snapshots__/Snackbar.unit.tsx.snap
- **[NEW]** Add support for onClick handler for `Caption` link.
- **[NEW]** Add support for replyLinkOnClick handler for `Review` reply link.
- **[FIX]** Fix `Button` height when using an HTML unstyled button.
Locally in storybook + simple unit tests
> Add onClick's support onClick for Review widget reply link

- CHANGELOG.md
- src/layout/section/slideSection/SlideSection.tsx
Small phone screens can't handle displaying both the map and the list, so we remove this layout position if the screen height is too small to handle it. The initial position will be with the list fully open by default for those screens, and you can only switch between this position, and the position where the media is fully shown. We also only show the GripHandle (with a small additional height for touch comfort) for the latter position.
Locally on Chrome, Firefox and Safari iOS (main reference for screen size: iPhone SE)
> Remove DEFAULT position for SlideSection on small screens

- CHANGELOG.md
- src/_internals/itineraryLocation/ItineraryLocation.tsx
- src/_internals/itineraryLocation/index.tsx
Fixed spacing on Connection Icon
Before | After
----|----
Added the missing margin from specs.
Nothing.
In storybook locally.
> Fixed spacing on Connection Icon

- CHANGELOG.md
- src/layout/section/itemsSection/__snapshots__/index.unit.tsx.snap
- src/layout/section/itemsSection/itemsSection.tsx
Forward the noHorizontalSpacing props to the BaseSection to normalise the ItemsSection component.
locally on storybook
> Add noHorizontalSpacing props on ItemsSection component

- CHANGELOG.md
- src/itinerary/Itinerary.tsx
- src/itinerary/Itinerary.unit.tsx
- src/itinerary/story.tsx
- Added new prop `segmentCollapsedLabel` so that we can display the correct number of stopover
See an example of usage here: https://github.com/blablacar/kairos/pull/4368/files
I went for the easiest solution without having to change the whole `Itinerary` component. 
We plan to do a bigger refacto to handle segments better in `Itinerary` I should be able to work on that next week.
In SPA through a canary version
> Added new prop for handling stopover on Itinerary segment

- src/hint/Hint.story.mdx
- src/hint/HintBubble.tsx
- src/hint/__snapshots__/Hint.unit.tsx.snap
Normalized `Hint`
Added missing horizontal margin on Hint component so that it has the correct outer spacing. 
Padding was already correct.
I couldn't use the `normalizeHorizontally` because it's only handling 2 cases: 
1. Components like Items that we can stack
2. Components like TripCard that will contain other components
This `Hint` component is a third case where the padding should be 16px (as stackable component) but also needs 24px margin.
Locally in storybook.
> Normalized Hint

- CHANGELOG.md
- src/searchRecap/__snapshots__/SearchRecap.unit.tsx.snap
- src/uneditableTextField/UneditableTextField.style.tsx
Removed `cursor: not-allowed` from `UneditableTextField`
Storybook
> Removed cursor: not-allowed from UneditableTextField

- CHANGELOG.md
- src/_utils/mediaSizeProvider/index.tsx
- src/_utils/mediaSizeProvider/index.unit.tsx
- Add new useIsSmallMediaSize and useIsLargeMediaSize custom hooks
- Add new mediaSizeForTestsOnly to set up the MediaSizeProvider in tests
Unit tests
> Add media size hooks and test set-up helper prop

- CHANGELOG.md
- src/selectField/index.tsx
Add missing`SelectFieldItem` type export
On kairos
> Add missing SelectFieldItem type export

- src/searchForm/baseStyles.tsx
Fix style override in `SearchForm`.
The issue only appears in production mode.
Use `!important` as quick fix, better fix would be not to use nested selectors for styles override, it breaks components isolation and introduce these kinds of errors.
Before | After
------ | ------
Nothing.
- Locally
> Fix SearchForm autocomplete styles

- CHANGELOG.md
- src/breadcrumb/Breadcrumb.story.mdx
- src/breadcrumb/Breadcrumb.style.tsx
- src/breadcrumb/Breadcrumb.tsx
- src/breadcrumb/Breadcrumb.unit.tsx
- src/breadcrumb/index.tsx
The Breadcrumb component on SEO pages will be moved from the top of the page to the bottom to make way for new content.
Hence, the ContentDivider that is included in Breadcrumb should shift from being below the actual breadcrumb to above. I also chose to create a case for no divider, which would be useful in the case of "directory pages" since the list of items ends with their own divider, so we wouldn't want to double that.
Tested locally on Firefox MacOs, with canary release
> [PROPIM-609] Add prop divider with DividerPosition enum to Breadcrumb

- CHANGELOG.md
- src/_internals/itineraryLocation/ItineraryLocation.tsx
- src/_internals/itineraryLocation/ItineraryLocation.unit.tsx
Everytime we were trying to pass `aria-label` to `SlugLink` in `place.href` the prop was getting overriden by the `pickA11yProps`. See here for more context: https://github.com/blablacar/kairos/pull/4487#discussion_r529610375
~We also reproduced it with `ItemChoice` `href` prop.~
As a long term fix we might want to replace `a11yProps` with `React.AriaAttributes` instead
@PerrineBoissieres We need your input on this.
Moved a11y props first so it doesn't override the aria-label passed 
This is a quick fix, I don't think other things will breaki
~In storybook by passing a component with `aria-label` in `ItemChoice` `href` prop.~
Unit test + Storybook
> Fixed aria props getting overriden

- CHANGELOG.md
- src/_utils/interfaces.ts
- src/hint/__snapshots__/Hint.unit.tsx.snap
- src/itemActionTitle/ItemActionTitle.unit.tsx
Remove `title` attribute from `A11yProps` added in the previous release (v41.10.0).
Some components like `Profile` already use `title` prop but for something else.
So we can't provide the `title` attribute globally for now, it require a global refacto/fix.
> Remove title attr from A11yProps

- CHANGELOG.md
- src/autoComplete/AutoComplete.unit.tsx
- src/autoComplete/AutoCompleteList.tsx
Use click event instead of mousedown to select an item in `AutoCompleteList`.
See ☝️
None.
- Storybook
- Unit tests
> Use click event to select an item in AutoCompleteList

- CHANGELOG.md
- src/layout/section/columnedContentSection/ColumnedContentSection.story.mdx
- src/layout/section/columnedContentSection/ColumnedContentSection.style.tsx
- src/layout/section/columnedContentSection/ColumnedContentSection.tsx
- src/layout/section/columnedContentSection/ColumnedContentSection.unit.tsx
We're adding a "USP" block on Bus landing pages that is basically the same as what we have on the homepage (a section with 3 columns, each with an icon/image and text).
I ask and we can change the Homepage block with these adjustments too.
Changes:
- icon is smaller (but that's not defined in ui-library), positioned on the left rather than in the center (except on small devices), all media have an added margin-bottom
- subtitle is now a paragraph instead of a heading (seo optimization)
- now using typography instead of Text/Title
- fixed columns gap when displaying less or more than 3 columns (not used but illustrated in the specs)
Tested on Firefox Macos, with canary release
> update title props & layout for ColumnedContentSection

- CHANGELOG.md
- src/searchForm/SearchForm.tsx
Automatically lead the user to the next field when he filled it.
- On large media, open the next field when it is empty after the user selected a value for the current one.
We don't do this on a small media because the open/close animations of the _modal_ can be confusing for the user.
- Locally
- With a canary release
> Autofocus next field in search form

- CHANGELOG.md
- src/phoneField/__snapshots__/PhoneField.unit.tsx.snap
- src/selectField/SelectField.tsx
- src/selectField/__snapshots__/SelectField.unit.tsx.snap
With OneAction & our kairos architecture, we can't be sure that the defaultValue will be correctly set a first render (race condition). Since defaultValue can't be updated after it's first rendering, we should use the `value`. We don't want to control this value from outside the component, so I just did as what we implemented in `TextArea` and `TextField`
Same as `TextArea` & `TextField`: use an internal state to handle value/default value
We might want to have controlled components someday? But that might require bigger updates in all the codebase
On kairos
> [BBC-11430] Handle `defaultValue` update in `SelectField`

- CHANGELOG.md
- src/layout/section/highlightSection/HighlightSection.style.tsx
- src/layout/section/highlightSection/HighlightSection.tsx
- src/layout/section/highlightSection/HighlightSection.unit.tsx
- src/layout/section/highlightSection/__snapshots__/HighlightSection.unit.tsx.snap
- src/subHeader/SubHeader.style.tsx
Let's reduce our `BaseSection` nesting by normalizing this component
Horizontal normalization
Vertical spacing is already matching the spec for this component
Kairos
> [BOYSCOUT] Normalize SubHeader

- CHANGELOG.md
- src/qrCard/QrCard.style.tsx
Normalization issues
Fixed:
Unfixed:
Removed padding on QrCard as `SubHeader` & `ItemInfo` already handles it.
storybook
> [BOYSCOUT] fix QrCard paddings

- CHANGELOG.md
- src/itinerary/Itinerary.style.tsx
- src/itinerary/Itinerary.tsx
Fix itinerary headline broken since `SubHeader` has been normalized
Stop using `SubHeader` as it comes with its default margin/padding that'll have to be overriden in this component.
Used `typography/SubHeaderStrong` instead, to keep consistent on the typography side. Added a h2 to keep the layout similar without breaking SEO, and re-added margins.
We should use typography components over "exposed" components to avoid these issues
storybook
> [BOYSCOUT] Fix itinerary headline display

- src/autoComplete/AutoCompleteList.tsx
- src/autoComplete/AutoCompleteListStyle.ts
- src/itemChoice/ItemChoice.tsx
- src/itemChoice/__snapshots__/index.unit.tsx.snap
- Fixed autocomplete keyboard navigation
- Removed non-Pixar style when list item gets highlighter with the keyboard
- Fixed tabbing issue
- Added `tabIndex` 0 on autocomplete list so we can't tab in the list, we can go through the list only using arrow up and down
- Simplified  `eventListener` on keyboard
- Used same style as hover on autocomplete list when navigating through the list with keyboard
Storybook + canary in Kairos
> Fixed autocomplete keyboard navigation

- CHANGELOG.md
- src/icon/checkCircleIcon.tsx
Added `background` prop to the icon. The name is chosen to match the pixar spec ("Check Circle + background")
Kairos
> Add background variation to CheckCircleIcon

- CHANGELOG.md
- src/_utils/mediaSizeProvider/index.tsx
- src/_utils/mediaSizeProvider/index.unit.tsx
- Fix initial flickering using useLayoutEffect (sync before first render) instead of useEffect (async)
- Introduce new serverSideMediaSize attribute to have a better media size default for server side rendered cases.
- Fix unsubscribing from debounced listener
- RTL tests
Unit tests, locally in kairos
> [BOYSCOUT] Fix MediaSizeProvider first render state

- CHANGELOG.md
- src/itemChoice/ItemChoice.tsx
Now matching `Item` types and allow strings
> Fix `ItemChoice` addons types

- CHANGELOG.md
- src/_utils/branding.ts
- src/icon/facebookIcon.tsx
Newest designs I got from the UX team used the updated Facebook logo and colors. VK also has a new color.
For reference:
https://en.facebookbrand.com/facebookapp/assets/f-logo/
https://vk.com/brand
So I updated these in the library.
> update FB and VK colors and icons

- src/marquee/Marquee.story.mdx
- src/marquee/Marquee.style.tsx
- src/marquee/Marquee.tsx
Missed the fact that if all items are in absolute positioning, there won't be a default height, hence I'm setting the first item to relative positioning.
Not perfect but it's meant as a "default" value that should be overridden if needed during the implementation of the Marquee, thus I'm also adding "className" to help in that case.
> update Marquee api name and style for height

- src/marquee/Marquee.story.mdx
- src/marquee/Marquee.style.tsx
Fixed horizontal spacing to match Paragraph, SubHeader, etc.
I had to paste the style for "normalizeHorizontally" cause it conflicted with the styled component's props
Tested on Firefox MacOS, storybook and canary
> update style and story to match use case

- CHANGELOG.md
- src/layout/section/mediaContentSection/__snapshots__/MediaContentSection.unit.tsx.snap
- src/review/__snapshots__/Review.unit.tsx.snap
- src/subHeader/SubHeader.story.mdx
- src/typography/Text.tsx
- src/typography/index.tsx
- src/typography/subHeader/SubHeader.story.mdx
- use knobs `text`
- split stories
-  Update text components to take `\n` into account
- SB
> [boyscout] Update SubHeader stories to play with `text`

- CHANGELOG.md
- src/filterBar/FilterBar.tsx
Export `FilterBarSupplyInfo` type and make `liquidity` more generic.
> Export FilterBarSupplyInfo type from FilterBar

- CHANGELOG.md
- src/dropdownButton/DropdownButton.story.mdx
- src/dropdownButton/DropdownButton.tsx
- src/hamburgerButton/HamburgerButton.story.mdx
- src/hamburgerButton/HamburgerButton.tsx
- src/menu/Menu.story.mdx
Added A11Y props to DropdownButton. I will need to add a dropdown that toggle a menu with 2 items, Login & Signup.
I want this dropdown to read something like "Connect" with screen readers but right now the API doesn't allow for this.
I also moved the DropdownButton out of the "Forms" category back to "Widgets" as it feels more appropriate regarding the way we use it.
Tested locally on Firefox MacOS with VoiceOver and a canary release.
> add a11y to DropdownButton and HamburgerButton

- CHANGELOG.md
- src/avatar/Avatar.style.tsx
- src/layout/section/illustratedSection/__snapshots__/IllustratedSection.unit.tsx.snap
- src/messagingSummaryItem/__snapshots__/MessagingSummaryItem.unit.tsx.snap
<Avatar isSmall /> made it 40x40px, slightly smaller than the normal size of 48x48px.
The "isSmall" variant is not used in the application so now I'm presented with an Avatar the size of an icon (24x24px) I simply changed the values.
Use case:
Note that it still works with the Badge:
Tested locally on Firefox MacOS and storybook.
> make Avatar isSmall smaller

- CHANGELOG.md
- src/_internals/colors.story.mdx
- src/_utils/branding.ts
- src/brandedVoice/BrandedVoice.story.mdx
- src/brandedVoice/BrandedVoice.style.tsx
- src/brandedVoice/BrandedVoice.tsx
- src/brandedVoice/BrandedVoice.unit.tsx
- src/brandedVoice/index.tsx
- src/icon/boostIcon.tsx
- src/typography/brand/Brand.story.mdx
- src/typography/brand/Brand.style.tsx
- src/typography/brand/index.tsx
- src/typography/typography.story.mdx
- **[NEW]** Add `BrandedVoice` component
- **[NEW]** Add `BlueGradient` in colors
- **[NEW]** Add `Brand` in typography
On small media:
On large media:
- Added `gradientColors` 
- Added new `TextBrand` display in typography
- I couldn't find a way to introduce a size between XL & XXL for our font sizes, so I just called it `brand`. Seems like we already had the case with `base`.
```
export const font: Font = {
s: {
size: '13px',
lineHeight: '16px',
},
base: {
size: '16px',
lineHeight: '20px',
},
m: {
size: '18px',
lineHeight: '20px',
},
l: {
size: '22px',
lineHeight: '24px',
},
xl: {
size: '30px',
lineHeight: String(Math.floor((32 / 30) * 100) / 100),
},
brand: {
size: '56px',
lineHeight: '56px',
},
xxl: {
size: '82px',
lineHeight: '82px',
},
}
```
- I'll like to use the `gradientColor` …
> New BrandedVoice component

- CHANGELOG.md
- src/phoneField/PhoneField.style.tsx
- src/phoneField/__snapshots__/PhoneField.unit.tsx.snap
- src/selectField/SelectField.style.tsx
- src/selectField/__snapshots__/SelectField.unit.tsx.snap
Fix unclickable down arrow on `SelectField` & `PhoneField`
- Keep the `<select>` tag above the `<svg>` tag (higher z-index)
- Keep the `<select>` tag transparent in case of error display to let the `<svg>` down arrow visible
With the fix:
https://www.loom.com/share/a0333adb84af432d805beaa8d9984320
Local environment with ui-library only (Chrome/FF/Safari)
> Fix SelectField and PhoneField down arrow

- CHANGELOG.md
- package-lock.json
- src/searchRecap/SearchRecap.style.tsx
- src/searchRecap/__snapshots__/SearchRecap.unit.tsx.snap
- src/uneditableTextField/UneditableTextField.style.tsx
- src/uneditableTextField/UneditableTextField.tsx
- src/uneditableTextField/UneditableTextField.unit.tsx
Horizontal normalization for `SearchRecap` & `UneditableTextField`
- Moved `UneditableTextField` React.createElement as a styled-component so that we can add styles to it.
- Removed horizontal padding from `SearchRecap`
Checking in Kairos now
In storybook
> Horizontal normalization on SearchRecap & UneditableTextField

- CHANGELOG.md
- src/paragraph/Paragraph.story.mdx
- src/paragraph/Paragraph.style.tsx
- src/paragraph/Paragraph.tsx
- src/paragraph/Paragraph.unit.tsx
- src/review/__snapshots__/Review.unit.tsx.snap
> BBC-12765 
This PR update `Paragraph` to accept ReactNode, which is usefull to render a paragraph with link inside.
But! As the expandable feature of `Paragraph` (when `isExpandable` is `true` only) use `substring` on the children,
I keep the `children: string` typing when `isExpandable` is `true`.
3 commits in this PR:
- 1st and 2nd about refactoring the component to use hooks and testing-library
- 3rd about enabling `ReactNode` for simple `Paragraph`'s `children`
Out of scope:
- accessibility updates: see https://blablacar.atlassian.net/browse/BBC-12577
UT
> [BBC-12765] Paragraph should accept ReactNode

- CHANGELOG.md
- src/layout/section/highlightSection/HighlightSection.story.mdx
- src/layout/section/highlightSection/HighlightSection.tsx
- src/layout/section/highlightSection/HighlightSection.unit.tsx
Changed the name of the highlighted items so it's less tied to product notions.
The highlights in HighlightSection were split in "axes" and "destinations", with "axes" being required.
It happens that the product now features blocks with only "destinations" so to make it less confusing, I'm renaming "axes => main" and "destinations = other" (you may suggest better names!)
I've also updated the data we use for tests and stories as it was confusing me a bit. Now test "destinations" are Spanish cities.
Locally on Firefox MacOS
> rename HighlightSection props for improved usage

- CHANGELOG.md
- src/index.tsx
- src/layout/section/faqSection/FaqSection.story.mdx
- src/layout/section/faqSection/FaqSection.style.tsx
- src/layout/section/faqSection/FaqSection.tsx
- src/layout/section/faqSection/FaqSection.unit.tsx
- src/layout/section/faqSection/index.tsx
Moved the FAQ block used on the Pro and Carpool home pages to ui-library, to better handle spacings.
Tested on Firefox MacOS with canary release (both /carpool and /pro pages)
> add FaqSection

- CHANGELOG.md
- src/itemAction/ItemAction.tsx
- src/itemAction/index.tsx
`ItemActionStatus` was not exported and we need it on SPA side.
> Export itemActionStatus

- CHANGELOG.md
- package-lock.json
- package.json
- src/fog/Fog.story.mdx
- src/fog/Fog.style.tsx
- src/fog/Fog.tsx
- src/fog/Fog.unit.tsx
- src/fog/index.tsx
- src/modal/Modal.style.tsx
- src/modal/index.tsx
- src/modal/storyUtils/ModalOpener.tsx
Moved ModalFog component as a generic component so we can use it anywhere.
- Created `Fog`
- Unit tests to make sure we can't click on elements underneath `Fog` when it is in loading state 
- Added a polyfill on `inert` attr for a11y since it's still an experimental feature in all browsers
Storybook + Unit test
> Moved ModalFog component as a generic component

- CHANGELOG.md
- src/_utils/interfaces.ts
- src/autoComplete/AutoComplete.story.mdx
- src/button/Button.tsx
- src/itemChoice/ItemChoice.tsx
- src/phoneField/__snapshots__/PhoneField.unit.tsx.snap
- src/textField/TextField.tsx
- src/textarea/Textarea.tsx
Add title and tabIndex to A11yProps
**If we add a `title` & `tabIndex` prop to the `Button` component:**
Unit tests + Storybook + Canary release
> Add title and tabIndex to A11yProps

- CHANGELOG.md
- src/_utils/branding.ts
- src/topBar/TopBar.example.tsx
- src/topBar/TopBar.story.mdx
- src/topBar/TopBar.style.tsx
- src/topBar/TopBar.tsx
- src/topBar/TopBar.unit.tsx
- src/topBar/drawer/Drawer.style.tsx
- src/topBar/drawer/Drawer.tsx
- src/topBar/drawer/Drawer.unit.tsx
The current TopBar has lots of style rules in the main app that should come from the ui-library component.
With that PR, only 2 rules remain, waiting for a more important refactoring of the component itself.
Also removed unnecessary style and added close() to the dimmer which is now included along with the drawer.
Tested locally on Firefox MacOS, with canary release
> import TopBar style from main app

- CHANGELOG.md
- src/icon/checkShieldIcon.tsx
Add backgroud prop to CheckShieldIcon
Local environment with ui-library + Canary release
> Add backgroud prop to CheckShieldIcon

- CHANGELOG.md
- src/newItinerary/Itinerary.style.tsx
- src/newItinerary/internals/Line.style.tsx
Video with problem & fix
https://user-images.githubusercontent.com/373381/113024550-2ad2c280-9187-11eb-8f28-a1088bc510fe.mp4
When a city name was too long and could not be naturally wrapped, it would take all the space, shrinking the time and line items. These 2 should not shrink.
> prevent itinerary from shrinking with long names

- CHANGELOG.md
- src/confirmationModal/ConfirmationModal.tsx
- src/modal/Modal.style.tsx
- src/modal/Modal.tsx
- src/modal/__snapshots__/Modal.unit.tsx.snap
- src/modal/storyUtils/ModalOpener.tsx
- src/successModal/SuccessModal.tsx
- src/successModal/SuccessModal.unit.tsx
**This PR fixe:**
- Don't Display the ModalFooter border if no scrollable content
- Keep bottom border-radius on no fullscreen display (desktop)
**Previous issues:**
**Footer border display without scrollable content:**
**Missing border-radius:**
**Modal with scrollable content - Display footer border**
https://www.loom.com/share/fb2363423caa428081842f8091b923ac
**Modal without scrollable content - Don't display footer border**
https://www.loom.com/share/5b34abcb3eff4e87beb480eecb523fe3
Local environment with ui-library + Canary release
> Fix ModalFooter display
