blablacar/ui-library

- CHANGELOG.md
- src/timePicker/style.ts
> Fix timePicker on small devices

- CHANGELOG.md
- src/itinerary/__snapshots__/index.unit.tsx.snap
- src/proximity/__snapshots__/index.unit.tsx.snap
- src/proximity/style.ts
Remove first margin-left
Before:
After:
> [BBCSPA-1544] adjust Proximity margins

- CHANGELOG.md
- __mocks__/exenv.js
- src/modal/__snapshots__/index.unit.tsx.snap
- src/modal/index.tsx
- src/modal/index.unit.tsx
- src/notification/__snapshots__/index.unit.tsx.snap
- src/notification/index.tsx
- src/notification/index.unit.tsx
This fixes all errors relative to server-side rendering of modals and notifications.
> Fix mismatch on SSR for modals and notifications

- README.md
* Fix syntactic coloration
* Add travis badge to show master's build status
> Fix syntactic coloration

- CHANGELOG.md
- src/text/index.tsx
- src/text/index.unit.tsx
- src/text/story.tsx
> Text component is now replacing new line by <br/> tags

- CHANGELOG.md
- src/_utils/branding.ts
- src/icon/facebookIcon.tsx
- src/icon/story.tsx
- src/icon/vkontakteIcon.tsx
I also added a story to see all icons:
> Use Facebook and VK brand color as default icon color

- CHANGELOG.md
- src/_utils/branding.ts
- src/button/index.tsx
- src/button/story.tsx
- src/modal/__snapshots__/index.unit.tsx.snap
- src/notification/__snapshots__/index.unit.tsx.snap
- src/stepper/index.tsx
- src/stepper/index.unit.tsx
- src/stepper/story.tsx
Manage mouseDown and mouseUp events on Stepper
> Update Stepper and Button to change value by keeping Buttons pressed

- CHANGELOG.md
- src/autoComplete/index.tsx
- src/autoComplete/index.unit.tsx
- src/autoComplete/story.tsx
The autocomplete component should be refactored but it requires too much work to be part of this PR.
It will be done in: BBCSPA-2041
> Autocomplete triggers a search on mount when a defaultValue is provided

- CHANGELOG.md
- src/itinerary/__snapshots__/index.unit.tsx.snap
- src/itinerary/index.tsx
- src/itinerary/index.unit.tsx
- src/itinerary/story.tsx
- src/itinerary/style.ts
- Props renaming
- CSS classes renaming
- Redesign of the from and to addon
> Update itinerary part 1

- CHANGELOG.md
- src/_utils/branding.ts
> Add brand colors for polyline

- CHANGELOG.md
- package-lock.json
- package.json
- src/checkbox/__snapshots__/index.unit.tsx.snap
- src/itinerary/__snapshots__/index.unit.tsx.snap
- src/modal/__snapshots__/index.unit.tsx.snap
- src/proximity/__snapshots__/index.unit.tsx.snap
- src/pushInfo/__snapshots__/index.unit.tsx.snap
- src/snackbar/__snapshots__/index.unit.tsx.snap
- src/uneditableTextField/__snapshots__/index.unit.tsx.snap
Breaks too many things, revert until we fix every issue with it.
> Revert styled-jsx update

- CHANGELOG.md
- src/itinerary/__snapshots__/index.unit.tsx.snap
- src/itinerary/index.tsx
We were missing some structured data on locations.
Before:
After:
> add location itemprop to Itinerary

- CHANGELOG.md
- src/snackbar/__snapshots__/index.unit.tsx.snap
- src/snackbar/index.tsx
- src/text/__snapshots__/index.unit.tsx.snap
- src/text/index.tsx
- src/text/index.unit.tsx
- src/textField/index.tsx
- src/textField/story.tsx
- Add possibility to have a role attribute on `<Text>`
- Add the role "alert" on `<Snackbar>` for accessibility
- Add aria-hidden on the `<Textfield>` clear button
> Improve accessibility of the textfield and snackbar

- CHANGELOG.md
- src/button/story.tsx
- src/button/style.ts
- src/modal/__snapshots__/index.unit.tsx.snap
- src/snackbar/__snapshots__/index.unit.tsx.snap
> [BBCSPA-2583] Support icon + text in button

- CHANGELOG.md
- src/_utils/item/__snapshots__/index.unit.tsx.snap
- src/_utils/item/index.tsx
- src/_utils/item/index.unit.tsx
**[FIX]** `Item` should not have an empty href on non `A` tags.
> Do not return href null when no href

- CHANGELOG.md
- src/icon/callIcon.tsx
- src/icon/index.tsx
- src/icon/sendIcon.tsx
| Call | Send |
|-----|------|
| ![image](https://user-images.githubusercontent.com/2495124/53242302-ad355200-36a4-11e9-8667-aeb5a045fe66.png) | ![image](https://user-images.githubusercontent.com/2495124/53242342-c0482200-36a4-11e9-9486-c58b99eafbdd.png) |
> [BBCSPA-2778] Add call and send icon

- CHANGELOG.md
- src/textField/index.tsx
- src/textField/index.unit.tsx
- src/textField/story.tsx
Added unit test, story and ran npm prettier.
> Update textfield state when formatting value after user text change

- CHANGELOG.md
- src/drawer/style.ts
The new animation spec (300ms) comes from the v3/dashvboard dimmer (confimed with Nico Duval).
> Add fade-in animation to drawer dimmer

- CHANGELOG.md
- src/icon/avatarIcon.tsx
- src/icon/flagsIcon.tsx
- src/icon/hourglassIcon.tsx
- src/icon/index.tsx
- src/icon/mapIcon.tsx
- src/icon/shareIcon.tsx
We should really do #221 someday.
> Add 5 icons

- CHANGELOG.md
- src/button/index.tsx
- src/buttonGroup/index.tsx
- src/buttonGroup/index.unit.tsx
- src/buttonGroup/specifications/index.md
- src/buttonGroup/story.tsx
- src/buttonGroup/style.ts
> Add loadingIndex property to ButtonGroup

- CHANGELOG.md
- src/avatar/index.tsx
- src/avatar/style.ts
- src/tripCard/index.tsx
- src/tripCard/index.unit.tsx
- src/tripCard/specifications/index.md
- src/tripCard/story.tsx
- src/tripCard/style.ts
- Added shadow
- Added badge option
- Added status information option 
- Added multiple passengers display
> TripCard component updates

- CHANGELOG.md
- src/tripCard/index.tsx
- src/tripCard/index.unit.tsx
- src/tripCard/story.tsx
> Add title option to TripCard

- CHANGELOG.md
- src/tripCard/style.ts
> Remove trip card border

- CHANGELOG.md
- src/icon/banIcon.tsx
- src/icon/index.tsx
> Add BanIcon

- CHANGELOG.md
- package-lock.json
- package.json
- src/tabs/__snapshots__/index.unit.tsx.snap
- src/tabs/index.tsx
- src/tabs/index.unit.tsx
- src/tabs/story.tsx
- src/tabs/style.ts
> Tabs update

- CHANGELOG.md
- src/messagingSummaryItem/__snapshots__/index.unit.tsx.snap
- src/messagingSummaryItem/index.tsx
- src/messagingSummaryItem/story.tsx
- src/messagingSummaryItem/style.ts
> Add support for html in sublabels for MessagingSummaryItem

- CHANGELOG.md
- src/_utils/branding.ts
- src/badge/index.tsx
- src/badge/index.unit.tsx
- src/tabs/__snapshots__/index.unit.tsx.snap
- src/tabs/index.tsx
- src/tabs/story.tsx
- src/tabs/style.ts
No visual change but allows for simpler customisation when used.
> update tabs (isWrapped, extend click area, Badge position)

- CHANGELOG.md
- src/message/style.ts
> Fix pointy corner on Message component.

- src/caption/Caption.tsx
- src/caption/Caption.unit.tsx
- src/caption/index.ts
> Migrate Caption to styled-component

- src/avatar/Avatar.tsx
- src/badge/Badge.tsx
- src/caption/Caption.tsx
- src/message/Message.tsx
- src/proximity/Proximity.tsx
- src/pushInfo/PushInfo.tsx
- src/text/Text.tsx
- src/title/Title.tsx
I left it on Snackbar for now, would need some more time to properly target the container classes
> remove all extraClassName except on Snackbar

- src/itemsList/ItemsList.tsx
Wrong case in ItemsList import ^^"
> Fix case issue with ItemRadio

- .babelrc
- CHANGELOG.md
- package-lock.json
- package.json
- src/_utils/item/Item.unit.tsx
- src/caption/index.tsx
- src/index.tsx
Removed all imports and dependencies to styled-jsx  🎉
> Remove styled-jsx from the project

- src/autoComplete/index.tsx
> Autocomplete fix

- CHANGELOG.md
- src/_utils/item/__snapshots__/Item.unit.tsx.snap
- src/confirmationModal/index.tsx
- src/itemCheckbox/__snapshots__/ItemCheckbox.unit.tsx.snap
- src/itemChoice/__snapshots__/index.unit.tsx.snap
- src/itemRadio/__snapshots__/ItemRadio.unit.tsx.snap
- src/itemRadioGroup/__snapshots__/index.unit.tsx.snap
- src/itemsList/__snapshots__/ItemsList.unit.tsx.snap
- src/messagingSummaryItem/__snapshots__/MessagingSummaryItem.unit.tsx.snap
- src/snackbar/__snapshots__/Snackbar.unit.tsx.snap
- src/text/index.tsx
Also invert DISPLAY1 and DISPLAY2 styles to comply with the design specification names
Previous
Now
Specs
> Fix font weight for DISPLAY1 and DISPLAY2

- CHANGELOG.md
- src/itinerary/Itinerary.tsx
> Itinerary change font weight of the headline to medium

- CHANGELOG.md
- src/datePicker/index.tsx
- src/datePicker/specifications/datepicker.md
> Add highlight for today date in datepicker

- CHANGELOG.md
- src/icon/detourIcon.tsx
- src/icon/index.tsx
> Add DetourIcon

- package-lock.json
- package.json
- src/icon/story.tsx
Also update Typescript and fix type issue
> Upgrade storybook to 5.2.1

- CHANGELOG.md
- src/button/index.tsx
- src/datePicker/__snapshots__/DatePicker.unit.tsx.snap
- src/dropdownButton/index.tsx
- src/hamburgerButton/index.tsx
- src/modal/__snapshots__/Modal.unit.tsx.snap
- src/phoneField/__snapshots__/PhoneField.unit.tsx.snap
- src/snackbar/__snapshots__/Snackbar.unit.tsx.snap
- src/toggleButton/index.tsx
> Add outline back on buttons

- CHANGELOG.md
- src/marketingMessage/index.tsx
> Fix right margin on marketing  messages

- CHANGELOG.md
- src/itemRadio/ItemRadio.tsx
- src/itemRadio/__snapshots__/ItemRadio.unit.tsx.snap
- src/itemRadio/index.tsx
- src/itemRadio/story.tsx
- src/itemRadioGroup/__snapshots__/index.unit.tsx.snap
- src/itemRadioGroup/index.tsx
- src/itemRadioGroup/index.unit.tsx
- src/theVoice/TheVoice.tsx
- src/theVoice/TheVoice.unit.tsx
- src/title/Title.tsx
- src/title/Title.unit.tsx
- Add `ariaLabelledby` property to `ItemRadioGroup`
- Add focus styles to `ItemRadio`
- Add `id` prop to `TheVoice` and `Title`
> Improve ItemRadio/ItemRadioGroup a11y

- CHANGELOG.md
- src/autoComplete/AutoComplete.tsx
- src/autoComplete/AutoComplete.unit.tsx
> Update no-results display in autocomplete component

- .travis.yml
- CHANGELOG.md
Without code analysis:
https://travis-ci.org/blablacar/ui-library/builds/628683694?utm_source=github_status&utm_medium=notification
With code analysis:
https://travis-ci.org/blablacar/ui-library/builds/628715866?utm_source=github_status&utm_medium=notification
> Fix travis code analysis

- CHANGELOG.md
- src/tripCard/TripCard.tsx
- src/tripCard/index.tsx
- src/tripCard/story.tsx
> Added ratings on tripCard

- CHANGELOG.md
- src/bullet/Bullet.tsx
- src/bullet/index.tsx
- src/bullet/story.tsx
> Update bullet styles for map

- CHANGELOG.md
- src/_utils/branding.ts
- src/_utils/checkboxIcon/__snapshots__/index.unit.tsx.snap
- src/_utils/icon/index.tsx
- src/_utils/item/__snapshots__/Item.unit.tsx.snap
- src/_utils/radioIcon/__snapshots__/index.unit.tsx.snap
- src/datePicker/__snapshots__/DatePicker.unit.tsx.snap
- src/icon/meetingPoint.tsx
- src/itemCheckbox/__snapshots__/ItemCheckbox.unit.tsx.snap
- src/itemChoice/__snapshots__/index.unit.tsx.snap
- src/itemRadio/__snapshots__/ItemRadio.unit.tsx.snap
- src/itemRadioGroup/__snapshots__/index.unit.tsx.snap
- src/itemsList/__snapshots__/ItemsList.unit.tsx.snap
- src/messagingSummaryItem/__snapshots__/MessagingSummaryItem.unit.tsx.snap
- src/modal/__snapshots__/Modal.unit.tsx.snap
- src/phoneField/__snapshots__/PhoneField.unit.tsx.snap
- src/proximity/__snapshots__/Proximity.unit.tsx.snap
- src/pushInfo/__snapshots__/PushInfo.unit.tsx.snap
- src/selectField/__snapshots__/SelectField.unit.tsx.snap
- src/snackbar/__snapshots__/Snackbar.unit.tsx.snap
- src/tabs/__snapshots__/Tabs.unit.tsx.snap
> Update MeetingPointIcon (new active state, optional shadow)

- CHANGELOG.md
- src/itinerary/Itinerary.tsx
- src/itinerary/Itinerary.unit.tsx
- src/itinerary/index.tsx
- src/itinerary/story.tsx
:'( 
This case is used in publication flow
> Add option to toggle road highlighting in Itinerary

- CHANGELOG.md
- src/datePicker/story.tsx
DAtepicker stories are broken since a few weeks (real datepicker is fine AFAIK).
> Fix broken Datepicker stories

- CHANGELOG.md
- src/_utils/itineraryCollapsible/ItineraryCollapsible.unit.tsx
- src/itinerary/Itinerary.tsx
- src/itinerary/Itinerary.unit.tsx
- src/itinerary/index.tsx
- src/itinerary/story.tsx
> Added rule on itinerary collapsible for displaying stopover directly

- CHANGELOG.md
- src/index.unit.tsx
- src/pages/messaging/brazemarketing.story.tsx
- src/pages/messaging/inbox.story.tsx
- src/pages/ridedetails/carpool.story.tsx
- stories/index.tsx
Create first BBC pages using the section system:
- ridedetails carpooling
- messaging inbox
- messaging marketing
> Create first kirk pages: ridedetails & messaging

- CHANGELOG.md
- src/layout/section/highlightSection/__snapshots__/index.unit.tsx.snap
- src/layout/section/highlightSection/highlightSection.tsx
- src/layout/section/highlightSection/index.tsx
- src/layout/section/highlightSection/index.unit.tsx
- src/layout/section/highlightSection/story.tsx
- src/layout/section/mediaContentSection/__snapshots__/index.unit.tsx.snap
- src/subHeader/SubHeader.tsx
- src/subHeader/SubHeader.unit.tsx
> Improve HighlightSection visual

- CHANGELOG.md
- src/layout/section/mediaContentSection/__snapshots__/index.unit.tsx.snap
- src/layout/section/mediaContentSection/index.tsx
- src/layout/section/mediaContentSection/mediaContentSection.tsx
- Add missing border radius
- Use <article> html tag
- Properly center image in small mode
- Left align title in large mode
> Fixes to mediaContentSection

- CHANGELOG.md
- src/layout/section/mediaContentSection/__snapshots__/index.unit.tsx.snap
- src/layout/section/mediaContentSection/index.tsx
- src/layout/section/mediaContentSection/story.tsx
- Fix text alignement and image position for all cases
- Add story for all cases
> Fix mediacontentsection v3

- CHANGELOG.md
- src/layout/section/tabsSection/__snapshots__/index.unit.tsx.snap
- src/tabs/index.tsx
> restore multiline fixed tabs

- CHANGELOG.md
- src/_utils/item/Item.tsx
- src/itemData/index.tsx
- src/pages/ridedetails/bus.story.tsx
- src/pages/ridedetails/carpool.story.tsx
- stories/index.tsx
> Added Bus Ride Details story page

- CHANGELOG.md
- src/pages/searchResults/tabs.story.tsx
- src/pages/yourrides/history.story.tsx
- src/pages/yourrides/rides.story.tsx
- src/tripCard/TripCard.tsx
- stories/index.tsx
> Add yourrides, ride history and SRP pages in kirk

- CHANGELOG.md
- src/timePicker/index.tsx
> Fix unclickable arrow in TimePicker

- CHANGELOG.md
- src/datePicker/index.tsx
- src/icon/calendarIcon.tsx
- src/icon/index.tsx
- src/index.unit.tsx
- src/searchForm/datePicker/datePickerFullScreen/DatePickerFullScreen.tsx
- src/searchForm/datePicker/datePickerFullScreen/DatePickerFullScreen.unit.tsx
- src/searchForm/datePicker/datePickerFullScreen/index.tsx
- src/searchForm/datePicker/datePickerOverlay/DatePickerOverlay.tsx
- src/searchForm/datePicker/datePickerOverlay/DatePickerOverlay.unit.tsx
- src/searchForm/datePicker/datePickerOverlay/index.tsx
- stories/stories.css
First step for the new search form layer
> Datepicker overlay & fullscreen

- CHANGELOG.md
- src/stepper/Stepper.tsx
- src/stepper/index.tsx
> Fixed layout issue on stepper button

- CHANGELOG.md
- src/layout/section/tripsSection/index.tsx
> fix TripsSection left scroll padding

- CHANGELOG.md
- src/itemInfo/index.tsx
- src/itemInfo/story.tsx
> Add aria label to ItemInfo, and aria-hidden to Item

- CHANGELOG.md
- src/stepper/Stepper.tsx
- src/stepper/Stepper.unit.tsx
- src/stepper/index.tsx
> Improve a11y on stepper for keyboard navigation and screen reader

- CHANGELOG.md
- package-lock.json
- src/layout/section/columnedContentSection/index.tsx
> Explicit margins for ColumnedContentSection

- CHANGELOG.md
- src/_utils/mediaSizeProvider/MediaSizeProvider.tsx
- src/_utils/mediaSizeProvider/MediaSizeProvider.unit.tsx
POC on react context to handle media size
> React context for media size

- package-lock.json
`found 39202 vulnerabilities (39177 low, 25 moderate)`
=>
`found 23 vulnerabilities (1 low, 22 moderate)`
> npm audit fix, update package-lock

- CHANGELOG.md
- src/autoComplete/AutoComplete.tsx
- src/bullet/Bullet.tsx
- src/bullet/index.tsx
- src/searchForm/autoComplete/overlay/AutoCompleteOverlay.tsx
- src/searchForm/autoComplete/overlay/AutoCompleteOverlay.unit.tsx
- src/searchForm/autoComplete/overlay/index.tsx
- src/searchForm/autoComplete/section/AutoCompleteSection.tsx
- src/searchForm/autoComplete/section/AutoCompleteSection.unit.tsx
- src/searchForm/autoComplete/section/index.tsx
- src/searchForm/story.tsx
**Overlay blank field**
**Overlay**
**Section**
> [BBC-6806] Add AutoCompleteOverlay and AutoCompleteSection

- CHANGELOG.md
- src/timePicker/TimePicker.tsx
- src/timePicker/index.tsx
- src/timePicker/story.tsx
> [BBC-7161] Create small version of Timepicker for filters

- CHANGELOG.md
- src/icon/index.tsx
- src/icon/zoomIn.tsx
- src/icon/zoomOut.tsx
> Add ZoomIn/ZoomOut icons

- CHANGELOG.md
- src/profile/index.tsx
- src/profile/profile.tsx
- src/profile/profile.unit.tsx
- src/profile/story.tsx
- Fix rendering for medium size (bottom align text content)
- improve story to show both sizes (small/medium)
- improve tests (use mount instead of shallow)
> Fix Profile medium rendering

- .github/CODEOWNERS.md
Code owners to improve PR reviews, notifications, and protection
> [BOYSCOUT] Ici cest SPA

- src/searchForm/SearchForm.tsx
- src/searchForm/SearchForm.unit.tsx
- src/searchForm/autoComplete/section/AutoCompleteSection.tsx
- src/searchForm/autoComplete/section/index.tsx
- src/searchForm/baseStyles.tsx
- src/searchForm/datePicker/section/index.tsx
- src/searchForm/index.tsx
- src/searchForm/stepper/section/StepperSection.tsx
- src/searchForm/stepper/section/StepperSection.unit.tsx
- src/searchForm/stepper/section/index.tsx
- src/searchForm/story.tsx
> Web Search Form: small devices interactions

- CHANGELOG.md
- src/layout/content/content.tsx
Fixes the warning about unsupported DOM attribute :)
> Fix DOM warning on MainContent

- CHANGELOG.md
- src/autoComplete/AutoComplete.tsx
- src/autoComplete/AutoCompleteList.tsx
- src/itemRadioGroup/__snapshots__/index.unit.tsx.snap
- src/itemsList/ItemsList.tsx
- src/itemsList/__snapshots__/ItemsList.unit.tsx.snap
- src/itemsList/index.tsx
- src/searchForm/baseStyles.tsx
Tested: visually with all the stories
> Use Divider component in ItemListDivider

- CHANGELOG.md
- src/autoComplete/AutoCompleteListStyle.ts
- src/layout/layoutNormalizer.tsx
Removed legacy autocomplete rules as per specs
> Removed autocomplete rules from layoutNormalizer

- CHANGELOG.md
- src/autoComplete/story.tsx
- src/searchForm/SearchForm.tsx
- src/searchForm/SearchForm.unit.tsx
- src/searchForm/autoComplete/overlay/AutoCompleteOverlay.tsx
- src/searchForm/autoComplete/overlay/AutoCompleteOverlay.unit.tsx
- src/searchForm/autoComplete/section/AutoCompleteSection.tsx
- src/searchForm/autoComplete/section/AutoCompleteSection.unit.tsx
- src/searchForm/baseStyles.tsx
- src/searchForm/story.tsx
- stories/index.tsx
- Added `autocompleteFrom` & `autocompleteTo` props
- Factorised `AutocompleteExample` for storybook
- Removed duplicated tests
> Search form with autocomplete

- CHANGELOG.md
- src/autoComplete/AutoComplete.tsx
- src/searchForm/SearchForm.tsx
- src/searchForm/SearchForm.unit.tsx
- src/searchForm/autoComplete/overlay/AutoCompleteOverlay.tsx
- src/searchForm/autoComplete/overlay/AutoCompleteOverlay.unit.tsx
- src/searchForm/autoComplete/overlay/index.tsx
- src/searchForm/autoComplete/section/AutoCompleteSection.tsx
- src/searchForm/autoComplete/section/AutoCompleteSection.unit.tsx
- src/searchForm/story.tsx
- Changed the way we render the autocomplete in based on https://github.com/blablacar/ui-library/pull/660/files#r408128422
- Cleaned up typescript typings
> Updated autocompleteProps to renderAutocomplete in Search Form

- CHANGELOG.md
- package-lock.json
- package.json
> [Release/v29.1.0] - Fix snapshots naming

- CHANGELOG.md
- package-lock.json
- package.json
- **[FIX]** Convert `SuccessModalProps` and `ModalProps` to type instead of interface; Resolve `ModalProps` path;
- **[FIX]** Fix breakpoints values to make them exclusive betweens small & large
- **[UPDATE]** Use focus & blur for improving keyboard navigation in `searchForm`
> [Release/v29.2.0] Fixes and Patchs

- CHANGELOG.md
- src/hint/HintBubble.tsx
- src/hint/__snapshots__/index.unit.tsx.snap
- src/hint/specifications/hint.md
- src/hint/story.tsx
The component doesn't have the good padding according to the Pixar specs/
*Specs*
*Prod*
- Fix the paddings
- Add a `flex: 1` to fix the button when the text is too long
Locally in storybook
> Bbc 7713/fix hint padding

- CHANGELOG.md
- src/successModal/elements.tsx
- src/successModal/story.tsx
Layout issues on text (centering) and spacements
**AFTER:**
https://www.loom.com/share/5294ccd2769d41d3aa4133c34ff7ff06
- `Knobs Text` for testing long/short textes and also `\n` possibilities
-  Some CSS polish to make sure image still 33% and text still be centered
- **Manually**
> [BOYSCOUT] Knobs for testing text and styling polish

- CHANGELOG.md
- src/successModal/elements.tsx
**BEFORE**
**AFTER**
- Convert `vh` into `%`
- Magic numbers from spec
- Manually 😬
> [HOTFIX] ScreenModal layout to  all browsers

- CHANGELOG.md
- __mocks__/matchMedia.ts
- src/_utils/useReducedMotion/index.tsx
- src/_utils/useReducedMotion/index.unit.tsx
- src/searchForm/SearchForm.tsx
- src/searchForm/SearchForm.unit.tsx
- src/searchForm/autoComplete/overlay/AutoCompleteOverlay.tsx
- src/searchForm/datePicker/overlay/DatePickerOverlay.tsx
- src/searchForm/datePicker/overlay/index.tsx
- src/searchForm/index.tsx
- src/searchForm/overlay/Overlay.tsx
- src/searchForm/overlay/index.tsx
- src/searchForm/stepper/overlay/StepperOverlay.tsx
- src/searchForm/stepper/overlay/index.tsx
- src/searchForm/story.tsx
Adding animation for search form on large layout.
Factorized repeated logic in an `Overlay` component.
Added animation using `CSSTransition` component. 
Added media query on `prefers-reduced-motion` to disable transition
Tested locally in storybook, updated unit test, and change MacOS settings to test `prefers-reduced-motion`
> Added animation in search form large devices

- CHANGELOG.md
- src/searchForm/SearchForm.tsx
- src/searchForm/SearchForm.unit.tsx
- src/searchForm/autoComplete/section/AutoCompleteSection.tsx
- src/searchForm/baseStyles.tsx
- src/searchForm/datePicker/section/DatePickerSection.tsx
- src/searchForm/overlay/Overlay.tsx
- src/searchForm/overlay/index.tsx
- src/searchForm/stepper/overlay/index.tsx
- src/searchForm/stepper/section/StepperSection.tsx
- src/searchForm/transitionConfig.tsx
Adding animations for small devices on search form
- Regroup animation config in the same file
- Used Styled component to share animation css between search form section components
- Added same z-index value as modals (temporary until we moved z-index logic from SPA to ui-lib)
- Used `position: fixed` instead of `absolute` so that it's top-positionned regardless of scroll in main document
There was no actual specs on this animation only a video, so this is a first shot at animation but will need to be discussed with UX designers.
Tested locally in storybook:
- desktop Chrome, Firefox, Safari.
- mobile Android Chrome
> Added Search form animations for large devices

- CHANGELOG.md
- src/tripCard/index.tsx
Introduced regression on Trip Card here #721 
Added same padding as itinerary
This is not really scalable but we're missing specs on this.
Locally in Storybook
> Fixed price position in trip card

- CHANGELOG.md
- src/_utils/item/__snapshots__/Item.unit.tsx.snap
- src/_utils/item/index.tsx
- src/itemCheckbox/__snapshots__/ItemCheckbox.unit.tsx.snap
- src/itemChoice/__snapshots__/index.unit.tsx.snap
- src/itemEditableInfo/index.tsx
- src/itemEditableInfo/index.unit.tsx
- src/itemEditableInfo/story.tsx
- src/itemRadio/__snapshots__/ItemRadio.unit.tsx.snap
- src/itemRadioGroup/__snapshots__/index.unit.tsx.snap
- src/itemsList/__snapshots__/ItemsList.unit.tsx.snap
- src/layout/section/itemsSection/__snapshots__/index.unit.tsx.snap
- src/messagingSummaryItem/__snapshots__/MessagingSummaryItem.unit.tsx.snap
- Add onClick to ItemEditableInfo
- Make clickable item use a cursor:pointer style
TESTED=Locally in storybook + unit tests
> Add onClick to ItemEditableInfo

- CHANGELOG.md
- src/_utils/item/__snapshots__/Item.unit.tsx.snap
- src/_utils/item/index.tsx
- src/itemCheckbox/__snapshots__/ItemCheckbox.unit.tsx.snap
- src/itemChoice/__snapshots__/index.unit.tsx.snap
- src/itemChoice/index.tsx
- src/itemChoice/index.unit.tsx
- src/itemChoice/story.tsx
- src/itemRadio/__snapshots__/ItemRadio.unit.tsx.snap
- src/itemRadioGroup/__snapshots__/index.unit.tsx.snap
- src/itemsList/__snapshots__/ItemsList.unit.tsx.snap
- src/layout/section/itemsSection/__snapshots__/index.unit.tsx.snap
- src/messagingSummaryItem/__snapshots__/MessagingSummaryItem.unit.tsx.snap
Use FocusVisibleContext to keep visual indicator when using keyboard navigation and remove it on pointer navigation.
Tested localy
> Fix Itemchoice focus issue

- CHANGELOG.md
- package-lock.json
- package.json
- **[NEW]** `RideAxis` component to display origin-destination
- **[NEW]** Component `ItemBigData` to display a specific and important data.
- **[UPDATE]** Use named exports instead of default exports.
- **[FIX]** Fix Focus issue on `ItemChoice` using `FocusVisibleContext`.
> [RELEASE] v34.4.0

- package-lock.json
- package.json
**missing version on package.json**
> [HOTFIX] Bump version

- CHANGELOG.md
- src/icon/redCircleIcon.tsx
Added `RedCircleIcon`
Tested on Button in Storybook
> Added red circle icon

- CHANGELOG.md
Fix wrong version number in changelog
> Fix wrong version number in changelog

- CHANGELOG.md
- stories/stories.css
Remove layout spacing that is no part of the components itself.
No custom CSS
- N/A
- local
> [BOYSCOUT] Remove spacing on canvas

- CHANGELOG.md
- src/loadingPage/LoadingPage.style.tsx
- src/loadingPage/__snapshots__/LoadingPage.unit.tsx.snap
simply adding a white background
tested locally with the main project
> Add white background to enable superposition

- CHANGELOG.md
- package-lock.json
- package.json
- **[NEW]** Add support for onClick handler for `Caption` link.
- **[NEW]** Add support for replyLinkOnClick handler for `Review` reply link.
- **[FIX]** Fix `Button` height when using an HTML unstyled button.
> Release v41.4.0

- tools/generator.js
- Fix index.tsx generator
- Folder starts with **lowercase**
- Components starts with **uppercase**
- Export `ComponentProps`
- local
> Scaffold index, force folder lowercase

- src/paragraph/Paragraph.story.mdx
Minor adjustment for discoverability. Move Paragraph to TEXT category
> [BBC-9082] Boyscout: Paragraph

- src/datePicker/DatePicker.story.mdx
- Separate DatePicker examples into Previews
- DatePicker on Forms Category
> [BOYSCOUT] DatePicker to Forms

- tools/component/component.story.mdx
- tools/component/index.tsx
- tools/generator.js
- Fixed directory case in story "usage" section
- Added ComponentProps to exported things in index
Using the command
> [BOYSCOUT] update scaffolding

- src/_internals/spacing.story.mdx
> Migrate spacings story to MDX

- src/layout/content/story.tsx
- src/paragraph/Paragraph.style.tsx
- src/review/Review.style.tsx
- src/review/Review.tsx
- src/review/__snapshots__/Review.unit.tsx.snap
Added normalized horizontal padding on `Paragraph`
- Added normalized horizontal padding on `Paragraph`
- Fixed impacted `Review` component
Working on the impacted SPA changes
Storybook locally
> Normalized Paragraph

- CHANGELOG.md
- src/buttonGroup/ButtonGroup.style.tsx
- Add horizontal normalization
- Add vertical normalization
In kairos, we're manually adding paddings (sometimes). We should harmonize this.
I know that some of them should be handled in the Button component, but it'll be another scale of development.
In kairos
> Normalize ButtonGroup

- CHANGELOG.md
- src/menu/Menu.tsx
Required to typescript UserMenu on kairos.
On kairos
> Add `A11yProps` to `Menu`

- CHANGELOG.md
- src/phoneField/index.tsx
Add the following missing re-exports:
- `PhoneFieldCustomCountryNames`
- `PhoneFieldOnChangeParameters`
> Add missing type exports from `PhoneField`

- CHANGELOG.md
- src/itemsList/ItemsList.tsx
- src/itemsList/ItemsList.unit.tsx
- src/itemsList/__snapshots__/ItemsList.unit.tsx.snap
- src/topBar/TopBar.tsx
- **[FIX]** Fix falsy values in `ItemsList`
- **[FIX]** Make input types in `TopBar` more flexible
Unit tests
> [BOYSCOUT] Fix some kirk types and APIs

- CHANGELOG.md
- src/button/Button.story.mdx
- src/button/Button.style.tsx
- src/button/Button.tsx
- src/datePicker/__snapshots__/DatePicker.unit.tsx.snap
- src/hint/__snapshots__/Hint.unit.tsx.snap
- src/layout/section/mediaContentSection/__snapshots__/MediaContentSection.unit.tsx.snap
- src/modal/__snapshots__/Modal.unit.tsx.snap
- src/phoneField/__snapshots__/PhoneField.unit.tsx.snap
- src/snackbar/__snapshots__/Snackbar.unit.tsx.snap
> add variants for Facebook and VK buttons

- src/tripCardSample/TripCardSample.story.mdx
- src/tripCardSample/TripCardSample.style.tsx
- src/tripCardSample/TripCardSample.tsx
- src/tripCardSample/TripCardSample.unit.tsx
Missing update from the feedback I got on https://github.com/blablacar/ui-library/pull/1074
> update TripCardSample with better style

- CHANGELOG.md
- src/phoneField/PhoneField.story.mdx
- src/phoneField/PhoneField.style.tsx
- src/phoneField/PhoneField.unit.tsx
- src/phoneField/__snapshots__/PhoneField.unit.tsx.snap
- src/selectField/SelectField.style.tsx
- src/selectField/__snapshots__/SelectField.unit.tsx.snap
Fix phonefield error state display
**Before the fix:**
--------------------------------------------------
**After:**
Local environment with ui-library only (Safari/Chrome/FF)
> Bbc 12388/fix phonefield error state

- CHANGELOG.md
- src/layout/pages/seaPage/seaPage.style.tsx
Remove background-color since illustration has 1px frame.
> [PROPIM-678](fix) Layout: remove background-color

- CHANGELOG.md
- src/icon/index.story.mdx
https://github.com/storybookjs/storybook/issues/8753
thanks @mcellier 
- SB
> [BBC-10882] Display icons on canvas

- CHANGELOG.md
- src/datePicker/DatePicker.style.tsx
DatePicker horizontal normalization 
Storybook + kairos (publish flow, edit flow, search page)
> Normalize DatePicker

- CHANGELOG.md
- src/layout/section/columnedContentSection/ColumnedContentSection.story.mdx
- src/layout/section/columnedContentSection/ColumnedContentSection.style.tsx
- src/layout/section/columnedContentSection/ColumnedContentSection.tsx
- src/layout/section/columnedContentSection/ColumnedContentSection.unit.tsx
- src/paragraph/Paragraph.story.mdx
Fix top link position on `ColumnedContentSection` and some refactoring.
I also removed a deprecated prop, not found anywhere in the main app.
On Firefox MacOS, with canary release
> fix top link on ColumnedContentSection

- CHANGELOG.md
- src/divider/contentDivider/ContentDivider.story.mdx
- src/divider/sectionDivider/SectionDivider.story.mdx
- src/divider/spacingDivider/SpacingDivider.story.mdx
- We were not able to view the 3 docs (only one of them)
- Fixed some list display
Storybook
> Fix dividers doc in storybook

- CHANGELOG.md
- src/_utils/icon/BaseIcon.tsx
- src/icon/chevronIcon.tsx
- src/phoneField/__snapshots__/PhoneField.unit.tsx.snap
- src/selectField/SelectField.tsx
- src/selectField/__snapshots__/SelectField.unit.tsx.snap
Fixed arrow direction on `SelectField`
Used the correct prop
TS should have caught this
Storybook
> Fixed arrow down on selectField

- src/specialOffer/SpecialOffer.style.tsx
> BBC-12076 
Now that we have real images to test, we can make those slight changes to accomodate the real size of the images.
Before: 
After:
Locally
> [BBC-12076] fix special offers sizing

- CHANGELOG.md
- src/loadingPage/__snapshots__/LoadingPage.unit.tsx.snap
- src/theVoice/TheVoice.story.mdx
- src/theVoice/TheVoice.style.tsx
- src/theVoice/TheVoice.tsx
- src/theVoice/TheVoice.unit.tsx
- src/typography/Text.tsx
Allow polymorphism for TheVoice component. Will help seach & seo pages to use normalize components with the right margins. 
- Stopped using <Title> for this component
- Use typography component for text
In theory we might be able to use `forwardedAs` from `styled-components` but i didn't succeed. Any idea?
Storybook
> Allow polymorphism of TheVoice component
